// Practice question bank for civics, law and economics.
// Every question records concept, difficulty, version, correct answer, explanation and source.
// The correct index is NEVER sent to the client before answering.
export const QUESTION_VERSION = 'tw-curriculum-2026-09-23';
export type Subject = 'civics' | 'law' | 'economics';
export type PracticeQuestion = {
  id: string; subject: Subject; concept: string;
  difficulty: 1 | 2 | 3; version: string;
  text: string; answers: string[]; correct: number;
  explanation: string; source: string;
};

export const QUESTIONS: PracticeQuestion[] = [
  // ── 法律 ──────────────────────────────────────────────────
  { id:'law-burden-1', subject:'law', concept:'civil-burden-of-proof', difficulty:2, version:QUESTION_VERSION,
    text:'民事訴訟中，主張對方違約的原告，原則上須做什麼？',
    answers:['由被告自行證明沒有違約','由原告提出支持主張的事實與證據','由法官主動蒐集所有證據','不需任何人舉證'],
    correct:1,
    explanation:'民事訴訟採「主張者舉證」原則（民事訴訟法第277條）：原告主張被告違約，須提出支持該主張的事實與證據，而非由被告自證清白。',
    source:'高中公民與社會教材；民事訴訟法第277條' },
  { id:'law-hearsay-1', subject:'law', concept:'evidence-types', difficulty:2, version:QUESTION_VERSION,
    text:'「我聽別人說他昨天偷了東西」，這句話在法庭上屬於哪種性質？',
    answers:['直接證據，可直接證明犯罪','傳聞證據，需查證原始來源','物證，法院必須採信','書面證據，效力最高'],
    correct:1,
    explanation:'轉述他人說法而非親眼見聞，屬傳聞（間接）證據，不能直接認定事實，須查證陳述的原始來源。',
    source:'高中公民與社會教材；刑事訴訟法傳聞法則相關條文' },
  { id:'law-innocence-1', subject:'law', concept:'presumption-of-innocence', difficulty:1, version:QUESTION_VERSION,
    text:'刑事訴訟中，「無罪推定原則」的意思是？',
    answers:['被告須自行證明無罪','被告在有罪確定前推定為無罪','有人指控即視為有罪','法官可依經驗直接認定'],
    correct:1,
    explanation:'無罪推定（刑事訴訟法第154條）：被告未經合法程序審判確定有罪前應被視為無罪，舉證責任在檢察官。',
    source:'中華民國憲法第8條；刑事訴訟法第154條；高中公民與社會教材' },
  { id:'law-juvenile-1', subject:'law', concept:'juvenile-protection', difficulty:2, version:QUESTION_VERSION,
    text:'少年事件處理法的主要目的是什麼？',
    answers:['盡快關押觸法少年以保護社會','以健全少年身心發展與保障其健全成長為優先','程序與成人刑事完全相同','由家長代替少年受罰'],
    correct:1,
    explanation:'少年事件處理法第1條：以保護處分優先，兼顧程序權利，目的在健全少年身心，而非單純懲罰。',
    source:'少年事件處理法第1條；高中公民與社會教材' },
  { id:'law-civil-criminal-1', subject:'law', concept:'civil-criminal-distinction', difficulty:2, version:QUESTION_VERSION,
    text:'下列何者最能區分民事訴訟與刑事訴訟？',
    answers:['民事由法院處理，刑事由警察處理','民事解決私人間權利義務爭議，刑事由國家追究犯罪責任','民事判決一定比刑事嚴重','民事必需律師，刑事不需要'],
    correct:1,
    explanation:'民事訴訟解決私人間財產、侵權等爭議；刑事訴訟是國家代表社會追究犯罪行為，兩者目的、程序與法律效果均不同。',
    source:'高中公民與社會教材；民事訴訟法與刑事訴訟法立法目的' },
  { id:'law-legalaid-1', subject:'law', concept:'legal-aid', difficulty:3, version:QUESTION_VERSION,
    text:'關於法律扶助制度，下列何者正確？',
    answers:['任何人都能免費取得律師協助，不需審查','資力不足且符合條件者可申請核准後獲律師協助','法律扶助只限刑事案件','律師可自行決定是否提供，不需申請'],
    correct:1,
    explanation:'法律扶助針對資力不足的當事人，須向法律扶助基金會申請並審查核准，適用於民事、刑事、行政等多種案件。',
    source:'法律扶助法；高中公民與社會教材' },
  { id:'law-causation-1', subject:'law', concept:'causation', difficulty:3, version:QUESTION_VERSION,
    text:'民事損害賠償成立，通常需要具備哪三個要素？',
    answers:['行為人的職業、受害人的年齡、損害金額','加害行為、損害結果、兩者間的因果關係','只需有損害結果即可','只要被告在場就可主張賠償'],
    correct:1,
    explanation:'民事侵權損害賠償須具備：加害行為（作為或不作為）、損害結果（實際損害）、兩者之間的相當因果關係，缺一不可。',
    source:'民法第184條；高中公民與社會教材' },
  { id:'law-contract-1', subject:'law', concept:'contract-formation', difficulty:2, version:QUESTION_VERSION,
    text:'依民法規定，契約成立的基本要件是？',
    answers:['一方提出要約，對方在有效期間內作出承諾','只需書面簽名即可','須經公證人認證才生效','必須有律師在場見證'],
    correct:0,
    explanation:'契約由要約（一方表示願意受拘束的意思）和承諾（他方同意）兩個意思表示合致而成立（民法第153條）。書面或公證並非一般契約成立的必要條件。',
    source:'民法第153條；高中公民與社會教材' },
  { id:'law-copyright-1', subject:'law', concept:'intellectual-property', difficulty:2, version:QUESTION_VERSION,
    text:'著作權在著作完成時即自動發生，不需要：',
    answers:['向主管機關申請登記','讓他人知道','公開發表','有書面記錄'],
    correct:0,
    explanation:'依著作權法第10條，著作人於著作完成時即享有著作權，不須向任何機關申請或登記，此稱「創作保護主義」。',
    source:'著作權法第10條；高中公民與社會教材' },
  { id:'law-consumer-1', subject:'law', concept:'consumer-protection', difficulty:2, version:QUESTION_VERSION,
    text:'消費者依消費者保護法，對企業經營者提出的商品瑕疵損害賠償，採取何種舉證原則？',
    answers:['消費者須自行舉證商品有瑕疵且因果關係成立','企業經營者須舉證商品無瑕疵（舉證責任倒置）','由法院職權調查，雙方均不需舉證','由主管機關先行認定'],
    correct:1,
    explanation:'消費者保護法採「舉證責任倒置」：消費者只需證明受有損害，舉證產品安全的責任在企業經營者，以平衡雙方資訊不對等。',
    source:'消費者保護法第7條；高中公民與社會教材' },
  { id:'law-agency-1', subject:'law', concept:'legal-representation', difficulty:3, version:QUESTION_VERSION,
    text:'未成年人（7歲以上）獨自簽訂的買賣契約，在法律上的效力為何？',
    answers:['完全無效，須重新簽訂','效力未定，須經法定代理人承認後才生效','完全有效，與成年人相同','依契約金額決定是否有效'],
    correct:1,
    explanation:'依民法第77條，限制行為能力人（7歲以上未成年）所為之法律行為，須經法定代理人之允許或事後承認；未允許或未承認時，效力未定。',
    source:'民法第77條；高中公民與社會教材' },
  { id:'law-tort-1', subject:'law', concept:'tort-liability', difficulty:2, version:QUESTION_VERSION,
    text:'甲故意毀損乙的財物，乙可依下列哪個法律請求損害賠償？',
    answers:['刑法——提起刑事告訴要求賠償','民法侵權行為——向甲請求賠償損失','行政訴訟——向法院提起行政訴訟','消費者保護法——向主管機關申訴'],
    correct:1,
    explanation:'民法第184條規定：因故意或過失不法侵害他人之權利者，負損害賠償責任。乙應提民事侵權訴訟請求賠償。刑事程序追究刑責，但不直接賠償被害人財損（須另附帶民事）。',
    source:'民法第184條；高中公民與社會教材' },
  { id:'law-appeal-1', subject:'law', concept:'judicial-remedy', difficulty:2, version:QUESTION_VERSION,
    text:'對第一審法院判決不服時，當事人可向哪個法院提出救濟？',
    answers:['向同一法院重新審判','向上級法院提起上訴','向行政院申訴','向監察院陳情'],
    correct:1,
    explanation:'我國採三級三審制：對第一審（地方法院）判決不服，可向第二審（高等法院）提起上訴；對第二審判決不服，再向第三審（最高法院）上訴。',
    source:'刑事訴訟法第344條；民事訴訟法第437條；高中公民與社會教材' },
  // ── 公民 ──────────────────────────────────────────────────
  { id:'civics-rights-1', subject:'civics', concept:'fundamental-rights', difficulty:1, version:QUESTION_VERSION,
    text:'依中華民國憲法，下列哪項是人身自由保障的核心內容？',
    answers:['人民可隨時拒繳任何稅款','人民非依法定程序不得逮捕、拘禁、審問、處罰','人民享有無限制的言論自由','政府機關不需授權即可搜查'],
    correct:1,
    explanation:'憲法第8條保障人身自由：人民非依法定程序不得逮捕、拘禁、審問或處罰，確保國家公權力有明確程序限制。',
    source:'中華民國憲法第8條；高中公民與社會教材' },
  { id:'civics-due-process-1', subject:'civics', concept:'due-process', difficulty:2, version:QUESTION_VERSION,
    text:'「正當法律程序」在法治國家的核心意義是？',
    answers:['多數人同意即可任意限制人民權利','國家限制人民自由須符合法定程序且有正當理由','程序只是形式，結果正確即可','只有法院需遵守程序'],
    correct:1,
    explanation:'正當法律程序要求國家行使公權力時須依合法程序、公平聽證與比例原則，保障人民不受任意對待，是法治國家的核心。',
    source:'中華民國憲法；司法院大法官解釋；高中公民與社會教材' },
  { id:'civics-separation-1', subject:'civics', concept:'separation-of-powers', difficulty:2, version:QUESTION_VERSION,
    text:'三權分立的主要目的是？',
    answers:['讓三機關互相競爭看效率','透過立法、行政、司法三權制衡，防止權力集中與濫用','確保所有政策由法院最終決定','讓行政統一指揮所有部門'],
    correct:1,
    explanation:'三權分立將國家權力分散於立法、行政、司法三機關並設計互相制衡機制，目的是防止任一機關濫用權力，保障人民自由與權利。',
    source:'中華民國憲法；高中公民與社會教材' },
  { id:'civics-election-1', subject:'civics', concept:'election-system', difficulty:2, version:QUESTION_VERSION,
    text:'台灣立法委員選舉採用的制度是？',
    answers:['單一選區制，每區選出多名','單一選區兩票制（區域＋不分區）','完全比例代表制','多數決複數選區制'],
    correct:1,
    explanation:'立法委員選舉採「單一選區兩票制」：一票投區域候選人（單一選區，相對多數當選），一票投政黨（依得票比例分配不分區席次），兼顧區域代表與比例原則。',
    source:'公職人員選舉罷免法；高中公民與社會教材' },
  { id:'civics-local-1', subject:'civics', concept:'local-autonomy', difficulty:2, version:QUESTION_VERSION,
    text:'地方自治的核心意義是？',
    answers:['地方政府可以不遵守中央法規','地方居民透過選舉自行管理地方公共事務','地方可以獨立對外締結國際條約','中央政府完全不干預地方'],
    correct:1,
    explanation:'地方自治指地方居民透過選舉產生代表，依法自行處理地方公共事務，是民主政治的重要基礎；但地方仍須遵守憲法與中央法令。',
    source:'地方制度法；中華民國憲法；高中公民與社會教材' },
  { id:'civics-remedy-1', subject:'civics', concept:'administrative-remedy', difficulty:3, version:QUESTION_VERSION,
    text:'人民對行政機關的處分不服，正確的行政救濟順序通常是？',
    answers:['直接到法院提行政訴訟','先提訴願，對訴願結果不服再提行政訴訟','向立法院陳情，由立委協調','向總統府申訴，請求特赦'],
    correct:1,
    explanation:'依訴願法與行政訴訟法，行政救濟通常先提訴願（向上級機關或原機關）；對訴願決定不服，再向行政法院提起行政訴訟，是目前主要的二階段救濟途徑。',
    source:'訴願法第1條；行政訴訟法；高中公民與社會教材' },
  { id:'civics-media-1', subject:'civics', concept:'media-literacy', difficulty:2, version:QUESTION_VERSION,
    text:'媒體素養的核心能力之一是？',
    answers:['相信所有媒體報導都完全客觀','能辨識資訊來源、分析報導立場並查核事實','只閱讀政府官方媒體','拒絕使用任何社群媒體'],
    correct:1,
    explanation:'媒體素養強調主動思辨：辨識媒體背後的立場與利益、比對多方來源、查核事實（fact-checking），避免被假新聞或片面報導影響判斷。',
    source:'高中公民與社會教材；媒體素養教育課程綱要' },
  { id:'civics-ngo-1', subject:'civics', concept:'civil-society', difficulty:2, version:QUESTION_VERSION,
    text:'公民社會（civil society）中，NGO（非政府組織）的主要特徵是？',
    answers:['由政府直接設立並控管','獨立於政府和企業之外，以公共利益為目的','以營利為主要目的','成員必須是政府官員'],
    correct:1,
    explanation:'NGO 是非政府、非營利的組織，獨立運作，通常以倡議公共議題、提供服務或推動社會變革為目的，是公民社會參與公共事務的重要形式。',
    source:'高中公民與社會教材；聯合國相關文件' },
  // ── 經濟 ──────────────────────────────────────────────────
  { id:'econ-supply-demand-1', subject:'economics', concept:'supply-demand', difficulty:1, version:QUESTION_VERSION,
    text:'當某商品市場需求增加而供給不變時，通常會發生什麼？',
    answers:['價格下降，數量減少','價格上升，均衡數量增加','價格不變，只有數量變化','供給自動減少以維持價格'],
    correct:1,
    explanation:'需求增加（需求曲線右移）在供給不變下，均衡價格上升、均衡數量增加，是市場價格機能的基本原理。',
    source:'高中經濟學教材；供給需求均衡分析' },
  { id:'econ-opportunity-cost-1', subject:'economics', concept:'opportunity-cost', difficulty:2, version:QUESTION_VERSION,
    text:'小明用2小時打工賺300元，但放棄了念書準備考試。這2小時打工的機會成本是？',
    answers:['零，因為賺到錢了','打工賺到的300元','放棄念書所損失的潛在利益（例如考試提分帶來的長遠收益）','交通費'],
    correct:2,
    explanation:'機會成本是做一選擇所放棄的次佳選擇之價值。選擇打工就放棄念書，機會成本是念書帶來的潛在收益，而非賺到的金額本身。',
    source:'高中經濟學教材；機會成本與選擇' },
  { id:'econ-externality-1', subject:'economics', concept:'market-failure', difficulty:3, version:QUESTION_VERSION,
    text:'工廠排放廢水污染河川卻不需付出代價，在經濟學上稱為？',
    answers:['完全競爭市場','外部性（負外部成本）','規模經濟','壟斷利潤'],
    correct:1,
    explanation:'外部性是市場失靈的一種：生產或消費行為對未參與交易的第三者造成影響，卻未反映在市場價格中。污染河川是典型的負外部成本。',
    source:'高中經濟學教材；市場失靈與政府干預' },
  { id:'econ-gdp-1', subject:'economics', concept:'gdp-growth', difficulty:2, version:QUESTION_VERSION,
    text:'GDP（國內生產毛額）衡量的是什麼？',
    answers:['一國所有居民的海外所得總和','一定期間內一個國家境內生產的所有最終商品與服務的市場價值','政府的稅收總額','一國所有企業的利潤加總'],
    correct:1,
    explanation:'GDP 是衡量一個國家（地區）在特定期間內，境內（不論生產者國籍）所生產的所有最終商品與服務的市場總價值，是衡量經濟規模與成長的主要指標。',
    source:'高中經濟學教材；行政院主計總處統計說明' },
  { id:'econ-inflation-1', subject:'economics', concept:'inflation-deflation', difficulty:2, version:QUESTION_VERSION,
    text:'通貨膨脹（inflation）對持有現金的人的影響是？',
    answers:['現金實質購買力上升，對持現金者有利','現金實質購買力下降，因為物價上漲了','沒有任何影響','現金面額會自動調整'],
    correct:1,
    explanation:'通貨膨脹代表物價普遍上漲，同樣金額的現金能買到的東西變少，即實質購買力下降。通膨對債務人較有利（還款負擔輕），對持現金或固定收益者不利。',
    source:'高中經濟學教材；中央銀行貨幣政策說明' },
  { id:'econ-monetary-1', subject:'economics', concept:'monetary-policy', difficulty:3, version:QUESTION_VERSION,
    text:'中央銀行提高利率，通常會產生什麼效果？',
    answers:['刺激消費與投資，促進經濟成長','抑制借貸與消費，有助降低通膨但可能減緩成長','直接增加政府稅收','讓股市立即上漲'],
    correct:1,
    explanation:'升息使借貸成本上升，抑制企業投資和消費者借款，進而降低總需求、抑制通膨；但也可能減緩經濟成長。這是緊縮性貨幣政策的典型工具。',
    source:'高中經濟學教材；中央銀行政策說明' },
  { id:'econ-fiscal-1', subject:'economics', concept:'fiscal-policy', difficulty:3, version:QUESTION_VERSION,
    text:'政府在景氣衰退時增加公共支出（如基礎建設），屬於哪種財政政策？',
    answers:['緊縮性財政政策','擴張性財政政策','中性財政政策','貨幣政策'],
    correct:1,
    explanation:'擴張性財政政策：政府增加支出或減稅，以刺激總需求、提振景氣。景氣衰退時採擴張政策，景氣過熱時採緊縮（減支出或加稅），這是「自動穩定機制」之外的主動干預。',
    source:'高中經濟學教材；財政部政策說明' },
  { id:'econ-trade-1', subject:'economics', concept:'international-trade', difficulty:2, version:QUESTION_VERSION,
    text:'「比較利益法則」說明國際貿易的基礎是？',
    answers:['只有絕對生產效率最高的國家才能出口','各國專注生產機會成本相對較低的商品再互相交換，雙方都能受益','貿易一定造成一國受益另一國受損','政府應完全禁止進口保護本國產業'],
    correct:1,
    explanation:'比較利益（comparative advantage）：即使一國在所有商品生產上都佔絕對優勢，只要各自專注生產機會成本較低的商品再交換，雙方都能消費到更多，這是自由貿易的理論基礎。',
    source:'高中經濟學教材；大衛・李嘉圖比較利益理論' },
  // ── 法律補充題 ────────────────────────────────────────────
  { id:'law-burden-2', subject:'law', concept:'civil-burden-of-proof', difficulty:1, version:QUESTION_VERSION,
    text:'「誰主張，誰舉證」是指？',
    answers:['被告有義務證明自己無罪','提出主張的一方須提供支持該主張的證據','法官必須主動為原告蒐集證據','律師可以替當事人偽造證據'],
    correct:1,
    explanation:'民事訴訟的舉證責任基本原則：提出主張的一方（通常是原告）須提出相應證據加以支持，對方不需反證，直到原告完成初步舉證。',
    source:'民事訴訟法第277條；高中公民與社會教材' },
  { id:'law-burden-3', subject:'law', concept:'civil-burden-of-proof', difficulty:2, version:QUESTION_VERSION,
    text:'某些特殊情形下，法律規定改由被告舉證（舉證責任倒置），下列哪個情境最符合？',
    answers:['一般普通侵權行為','公害訴訟或醫療糾紛，因資訊不對稱而轉換舉證責任','所有民事訴訟一律由被告舉證','刑事案件由被告證明清白'],
    correct:1,
    explanation:'在公害、醫療等資訊嚴重不對等的案件，法律或判例要求由被告（加害方）舉證其行為無過失或因果關係不存在，稱為舉證責任轉換或倒置。',
    source:'消費者保護法；高中公民與社會教材' },
  { id:'law-burden-4', subject:'law', concept:'civil-burden-of-proof', difficulty:3, version:QUESTION_VERSION,
    text:'甲主張乙借錢未還，但找不到借據。下列何者正確？',
    answers:['因無書面借據，甲必然敗訴','甲可以其他方式（如轉帳紀錄、通訊紀錄）代替書面證明','乙須自行證明沒有借錢','法院不受理無書面證據的案件'],
    correct:1,
    explanation:'民事訴訟舉證方式不限於書面，各種適法證據均可採用，包括金融轉帳紀錄、簡訊、通話錄音等，只要達到使法官形成心證的程度即可。',
    source:'民事訴訟法第277條；最高法院相關判例；高中公民與社會教材' },
  { id:'law-burden-5', subject:'law', concept:'civil-burden-of-proof', difficulty:2, version:QUESTION_VERSION,
    text:'民事舉證責任分配的依據，主要是哪一條文？',
    answers:['憲法第16條訴訟權','民事訴訟法第277條','刑事訴訟法第154條','民法第148條'],
    correct:1,
    explanation:'民事訴訟法第277條規定：當事人主張有利於己之事實者，就其事實有舉證之責任，但法律別有規定，或依其情形顯失公平者，不在此限。',
    source:'民事訴訟法第277條；高中公民與社會教材' },
  { id:'law-hearsay-2', subject:'law', concept:'evidence-types', difficulty:1, version:QUESTION_VERSION,
    text:'「直接證據」與「間接（情況）證據」的主要區別是？',
    answers:['直接證據只限書面文件；間接證據只限人證','直接證據可直接證明犯罪事實；間接證據須與其他事實結合才能推論','直接證據一定比間接證據可信','間接證據在法庭上完全不能使用'],
    correct:1,
    explanation:'直接證據（如目擊者親眼所見）可直接指向犯罪事實；間接（情況）證據本身無法直接證明，須結合多個環境事實加以推論，兩者均可成為定罪依據。',
    source:'刑事訴訟法；高中公民與社會教材' },
  { id:'law-hearsay-3', subject:'law', concept:'evidence-types', difficulty:2, version:QUESTION_VERSION,
    text:'警察在犯罪現場找到的帶有指紋的凶器，屬於哪種證據？',
    answers:['傳聞證據','書面證據','物證（實物證據）','鑑定意見'],
    correct:2,
    explanation:'物證（實物證據）是指與案件相關的實體物品，如凶器、指紋、現場遺留物。物證不需通過人的陳述，可直接呈庭作為法院認定事實的依據。',
    source:'刑事訴訟法；高中公民與社會教材' },
  { id:'law-hearsay-4', subject:'law', concept:'evidence-types', difficulty:3, version:QUESTION_VERSION,
    text:'傳聞法則的主要目的是？',
    answers:['讓所有目擊者都不必出庭','確保當事人有機會對不利陳述進行對質詰問，保障訴訟公平性','規定所有證據必須是書面形式','要求法院只採用物證'],
    correct:1,
    explanation:'傳聞法則排除庭外陳述作為證據，是為了保障被告的對質詰問權：當庭外陳述被引用時，被告無法直接詰問原始陳述者的可信度，故原則排除，例外允許。',
    source:'刑事訴訟法第159條以下；高中公民與社會教材' },
  { id:'law-hearsay-5', subject:'law', concept:'evidence-types', difficulty:2, version:QUESTION_VERSION,
    text:'鑑定意見（如法醫報告）在訴訟中屬於哪種性質的證據？',
    answers:['傳聞證據，一律排除','專業人士依其學識所作之判斷意見，屬人證的一種形式','物證','直接目擊證詞'],
    correct:1,
    explanation:'鑑定意見是由具備專業知識的鑑定人，就特定事項（如死因、筆跡、血跡）提出的判斷，屬於人證（意見證據）的特殊形式，法院須評估鑑定方法的可信度。',
    source:'刑事訴訟法第197條以下；高中公民與社會教材' },
  { id:'law-innocence-2', subject:'law', concept:'presumption-of-innocence', difficulty:2, version:QUESTION_VERSION,
    text:'無罪推定原則下，刑事案件的舉證責任在誰身上？',
    answers:['被告須自行舉證無罪','由檢察官舉證被告有罪','被害人舉證被告的不法行為','由法官主動調查決定'],
    correct:1,
    explanation:'無罪推定要求控方的舉證達到排除合理懷疑的標準，舉證責任在國家（檢察官），被告無義務自證無罪。',
    source:'刑事訴訟法第154條、第161條；高中公民與社會教材' },
  { id:'law-innocence-3', subject:'law', concept:'presumption-of-innocence', difficulty:1, version:QUESTION_VERSION,
    text:'「疑罪從無」原則是指？',
    answers:['案件有疑義時應加重刑罰','檢察官存有合理懷疑時不應起訴或法院應判無罪','疑義時由被害人自行決定','被告可以選擇不出庭'],
    correct:1,
    explanation:'疑罪從無是無罪推定的延伸：當控方提出的證據不足以排除合理懷疑時，應作出對被告有利的認定，即判無罪，而非定一點罪。',
    source:'刑事訴訟法第154條；高中公民與社會教材' },
  { id:'law-innocence-4', subject:'law', concept:'presumption-of-innocence', difficulty:3, version:QUESTION_VERSION,
    text:'媒體在審判前大量報導「犯罪嫌疑人」的行為，與無罪推定有何衝突？',
    answers:['沒有衝突，媒體報導是言論自由','可能形成輿論壓力，影響司法公正性並侵害當事人被視為無罪的權利','可以加速司法程序','有利於被告辯護'],
    correct:1,
    explanation:'審判前的媒體「公審」可能造成公眾先入為主的有罪印象，對法官形成壓力，侵害被告接受公正審判的權利，與無罪推定原則相衝突。',
    source:'公民與政治權利國際公約；高中公民與社會教材' },
  { id:'law-innocence-5', subject:'law', concept:'presumption-of-innocence', difficulty:2, version:QUESTION_VERSION,
    text:'下列何者體現了無罪推定原則？',
    answers:['被告須在開庭前先繳保釋金才能自由','法院在判決確定前不得稱被告為「罪犯」','被告被起訴即代表已定罪','被告必須接受測謊才能主張無罪'],
    correct:1,
    explanation:'在判決確定有罪前，被告在法律上仍應被視為「無罪之人」，媒體或官方不應以「罪犯」稱之，這是無罪推定原則的具體實踐。',
    source:'刑事訴訟法第154條；高中公民與社會教材' },
  { id:'law-juvenile-2', subject:'law', concept:'juvenile-protection', difficulty:1, version:QUESTION_VERSION,
    text:'少年事件處理法規定，少年觸法案件由哪個機構處理？',
    answers:['普通地方法院刑事庭','少年法院（或地方法院少年法庭）','行政機關直接裁罰','由家長決定處置方式'],
    correct:1,
    explanation:'依少年事件處理法，少年觸犯刑罰法律或有偏差行為，應由少年法院（或各地地方法院少年法庭）以保護優先的程序處理，而非一般刑事法庭。',
    source:'少年事件處理法第3條；高中公民與社會教材' },
  { id:'law-juvenile-3', subject:'law', concept:'juvenile-protection', difficulty:2, version:QUESTION_VERSION,
    text:'少年保護處分的常見種類不包含下列哪項？',
    answers:['訓誡並予假日生活輔導','安置輔導','感化教育','處以成人無期徒刑'],
    correct:3,
    explanation:'少年事件處理法的保護處分包括訓誡、假日輔導、保護管束、安置輔導、感化教育等，以矯正輔導為主；成人刑罰（如無期徒刑）不適用於少年保護事件。',
    source:'少年事件處理法第42條；高中公民與社會教材' },
  { id:'law-juvenile-4', subject:'law', concept:'juvenile-protection', difficulty:3, version:QUESTION_VERSION,
    text:'未滿14歲的兒童觸法，依我國法律如何處理？',
    answers:['與成人相同，依刑法追訴','依刑法不罰，但可依少年事件處理法裁定保護處分','完全不追究任何責任','由學校自行懲處'],
    correct:1,
    explanation:'刑法第18條規定未滿14歲不罰，但少年事件處理法仍可對其裁定保護處分（如安置、感化教育），兼顧保護與矯正，並非完全放任。',
    source:'刑法第18條；少年事件處理法；高中公民與社會教材' },
  { id:'law-juvenile-5', subject:'law', concept:'juvenile-protection', difficulty:2, version:QUESTION_VERSION,
    text:'少年事件的審理為何不公開？',
    answers:['為了節省法院資源','保護少年隱私，避免標籤效應影響其未來發展','讓家長無從監督','減少律師的介入'],
    correct:1,
    explanation:'少年事件處理法規定審理原則上不公開，主要目的是保護少年隱私，避免社會標籤使其難以回歸正常生活，符合「最佳利益兒少」的保護精神。',
    source:'少年事件處理法第34條；高中公民與社會教材' },
  { id:'law-civil-criminal-2', subject:'law', concept:'civil-criminal-distinction', difficulty:1, version:QUESTION_VERSION,
    text:'民事訴訟的原告通常是誰？',
    answers:['國家或檢察官','私人（自然人或法人）','警察機關','行政機關'],
    correct:1,
    explanation:'民事訴訟解決私人間的法律爭議，由受害的私人（自然人或法人）自行作為原告提起訴訟；刑事訴訟則由代表國家的檢察官提起公訴。',
    source:'民事訴訟法；高中公民與社會教材' },
  { id:'law-civil-criminal-3', subject:'law', concept:'civil-criminal-distinction', difficulty:2, version:QUESTION_VERSION,
    text:'同一件傷害事件，可能同時涉及民事與刑事責任，下列何者正確？',
    answers:['處理了刑事責任就自動解決民事賠償','民事賠償和刑事追訴是獨立的程序，可同時進行','只能選一種程序提起，不能同時','有民事賠償就不需刑事追訴'],
    correct:1,
    explanation:'同一行為可同時構成刑事犯罪（國家追訴）和民事侵權（受害人求償），兩種程序並行不悖。被告可能被判刑並同時需賠償被害人損失。',
    source:'高中公民與社會教材；刑事附帶民事訴訟制度' },
  { id:'law-civil-criminal-4', subject:'law', concept:'civil-criminal-distinction', difficulty:3, version:QUESTION_VERSION,
    text:'民事訴訟和刑事訴訟的舉證標準不同，下列何者正確？',
    answers:['兩者都要求排除合理懷疑','民事訴訟通常採「優勢證明」標準，刑事訴訟採「排除合理懷疑」標準','刑事訴訟只需優勢證明','民事要求的標準比刑事更嚴格'],
    correct:1,
    explanation:'刑事訴訟因後果嚴重（剝奪人身自由）要求較高的「排除合理懷疑」標準；民事訴訟通常只要「優勢證明」（即一方的主張比對方更可能為真），兩者標準不同。',
    source:'高中公民與社會教材；刑事訴訟法；民事訴訟法' },
  { id:'law-civil-criminal-5', subject:'law', concept:'civil-criminal-distinction', difficulty:2, version:QUESTION_VERSION,
    text:'刑事案件中，被害人想要獲得金錢賠償，應如何做？',
    answers:['刑事判決自動包含賠償，無需另行主張','在刑事訴訟中附帶提起民事賠償訴訟，或另行提起民事訴訟','向檢察官申請賠償金','向法務部申請'],
    correct:1,
    explanation:'刑事程序本身只追究刑責（徒刑、罰金等）；被害人若要獲得金錢賠償，必須附帶提起民事訴訟（刑事附帶民事）或另外提起獨立民事訴訟。',
    source:'刑事訴訟法第487條；高中公民與社會教材' },
  { id:'law-legalaid-2', subject:'law', concept:'legal-aid', difficulty:1, version:QUESTION_VERSION,
    text:'台灣提供法律扶助的主要機構是？',
    answers:['法務部法律事務所','法律扶助基金會','警察局法律諮詢室','各縣市稅捐稽徵處'],
    correct:1,
    explanation:'法律扶助基金會（設於各縣市）是台灣提供法律扶助的主要機構，對資力不足且案件具扶助必要者，提供律師代理、諮詢等服務。',
    source:'法律扶助法；高中公民與社會教材' },
  { id:'law-legalaid-3', subject:'law', concept:'legal-aid', difficulty:2, version:QUESTION_VERSION,
    text:'法律扶助申請的審查重點通常包含？',
    answers:['只看當事人的學歷','資力（財產與收入）不足，以及案件是否符合法定要件','只要是刑事案件一律通過','任何人申請都會通過'],
    correct:1,
    explanation:'申請法律扶助須通過兩項審查：一是資力審查（收入與財產低於一定標準），二是案件審查（案件有扶助必要且非顯無理由），通過後才指派律師。',
    source:'法律扶助法第14條；高中公民與社會教材' },
  { id:'law-legalaid-4', subject:'law', concept:'legal-aid', difficulty:3, version:QUESTION_VERSION,
    text:'刑事訴訟中，哪種情形法院必須為被告強制辯護（指定義務辯護人）？',
    answers:['所有刑事案件','所犯為死刑、無期徒刑或最輕本刑三年以上有期徒刑案件，且被告未自行委任辯護人','僅在被告申請時才指定','只有外國籍被告需要'],
    correct:1,
    explanation:'刑事訴訟法規定，所犯為死刑、無期徒刑或最輕本刑三年以上有期徒刑的案件（強制辯護案件），若被告未自行委任律師，法院必須指定公設辯護人，保障被告的辯護權。',
    source:'刑事訴訟法第31條；高中公民與社會教材' },
  { id:'law-legalaid-5', subject:'law', concept:'legal-aid', difficulty:2, version:QUESTION_VERSION,
    text:'法律扶助制度的主要目的是？',
    answers:['讓有錢人能免費打官司','確保資力不足者也能平等獲得司法保護，實現程序正義','讓律師有更多工作機會','縮減法院案件量'],
    correct:1,
    explanation:'法律扶助制度旨在解決「有錢才有正義」的問題，確保經濟弱勢者在面對法律糾紛時，同樣能獲得專業法律協助，實現程序上的平等正義。',
    source:'法律扶助法第1條；高中公民與社會教材' },
  { id:'law-causation-2', subject:'law', concept:'causation', difficulty:1, version:QUESTION_VERSION,
    text:'民法上「相當因果關係」是指什麼？',
    answers:['任何遙遠的原因都可請求賠償','依一般社會觀念，該行為通常可能引起該損害結果','純屬巧合的關係','只有直接原因才算'],
    correct:1,
    explanation:'相當因果關係：若依一般生活經驗，某行為「通常」或「相當可能」產生某種損害結果，則兩者之間有相當因果關係，可成立侵權損害賠償。',
    source:'民法第184條；最高法院相關判例；高中公民與社會教材' },
  { id:'law-causation-3', subject:'law', concept:'causation', difficulty:2, version:QUESTION_VERSION,
    text:'甲開車不慎撞傷乙，乙因傷住院。乙的醫療費用與甲行為的因果關係如何評斷？',
    answers:['甲不需負責，因為是乙自己上路的風險','甲的過失行為與乙的受傷有相當因果關係，甲應賠償醫療費','醫院的醫療行為才是真正原因','乙須自行負擔，因為甲也是意外'],
    correct:1,
    explanation:'甲的過失駕駛行為引發車禍，乙因此受傷住院，兩者間有直接且相當的因果關係；醫療費是損害的一部分，甲需一併賠償。',
    source:'民法第184條、第193條；高中公民與社會教材' },
  { id:'law-causation-4', subject:'law', concept:'causation', difficulty:3, version:QUESTION_VERSION,
    text:'「假設的因果關係」（即使無甲行為，損害也會發生）在侵權責任上的效果是？',
    answers:['甲必然免責','不影響甲的責任，加害行為與損害間的因果關係已成立，後來的假設情況不能追溯免責','加重甲的責任','使損害賠償金額加倍'],
    correct:1,
    explanation:'假設因果關係不能免除甲的賠償責任；侵權責任以現實發生的因果為準，假設情形不能溯及免責。',
    source:'民法第184條；高中公民與社會教材；侵權法理論' },
  { id:'law-causation-5', subject:'law', concept:'causation', difficulty:2, version:QUESTION_VERSION,
    text:'下列哪種情形，甲通常「不需」對乙的損害負因果責任？',
    answers:['甲故意破壞乙的財物','甲的行為與乙的損害純屬巧合，兩者無相當因果關係','甲過失傷害乙','甲違反安全規範導致乙受傷'],
    correct:1,
    explanation:'若甲的行為與乙的損害之間只是偶然的時間巧合，依一般社會觀念無法認為甲的行為「通常」會導致乙的損害，則因果關係不成立，甲不需負賠償責任。',
    source:'民法第184條；最高法院相關判例；高中公民與社會教材' },
  { id:'law-contract-2', subject:'law', concept:'contract-formation', difficulty:1, version:QUESTION_VERSION,
    text:'口頭約定是否具有法律效力？',
    answers:['完全無效，契約必須書面才有效','原則上有效，但特定契約依法須以書面為之','只在雙方都有目擊者時有效','口頭約定只能作為參考，不能打官司'],
    correct:1,
    explanation:'民法契約自由原則：契約原則上不要求書面形式，口頭合意即可成立並有效；但法律有特別規定（如不動產買賣、保證契約）才要求書面形式。',
    source:'民法第153條；高中公民與社會教材' },
  { id:'law-contract-3', subject:'law', concept:'contract-formation', difficulty:2, version:QUESTION_VERSION,
    text:'超市展示的商品標示價格，對消費者而言屬於？',
    answers:['要約，消費者拿起商品即契約成立','要約引誘（誘引顧客提出要約）','承諾','締約前義務'],
    correct:1,
    explanation:'商品陳列與標價通常被認為是「要約的引誘」，邀請消費者提出要約（拿到結帳處付款）；店家承諾（收款）後契約才成立。',
    source:'民法第154條；高中公民與社會教材' },
  { id:'law-contract-4', subject:'law', concept:'contract-formation', difficulty:3, version:QUESTION_VERSION,
    text:'甲以詐欺手段使乙簽訂契約，乙的救濟方式是？',
    answers:['契約當然無效，不需任何行動','乙可在1年除斥期間內以意思表示撤銷契約（民法第92條）','乙只能請求損害賠償，無法撤銷','須由法院主動宣告無效'],
    correct:1,
    explanation:'民法第92條：因被詐欺或脅迫而為意思表示者，表意人得撤銷其意思表示。撤銷後契約溯及消滅，乙可請求回復原狀並請求損害賠償。',
    source:'民法第92條；高中公民與社會教材' },
  { id:'law-contract-5', subject:'law', concept:'contract-formation', difficulty:2, version:QUESTION_VERSION,
    text:'契約成立後，何種情形下當事人可以解除契約？',
    answers:['任何時候都可以單方面解除','僅在法律有規定或契約有明訂解除條款，且符合條件時，方可解除','只要通知對方即可','解除必須經法院裁定'],
    correct:1,
    explanation:'契約成立後對雙方均有拘束力（民法第153條），單方解除需有法定原因（如給付遲延、給付不能）或契約約定的解除條款；任意解除對方可請求損害賠償。',
    source:'民法第254條、第256條；高中公民與社會教材' },
  { id:'law-copyright-2', subject:'law', concept:'intellectual-property', difficulty:1, version:QUESTION_VERSION,
    text:'著作權保護的是什麼？',
    answers:['所有的想法和概念','具有原創性且已表達出來的著作（文字、音樂、美術等）','產品的外觀設計（屬商標或專利）','所有自行創作的資訊'],
    correct:1,
    explanation:'著作權保護「表達」而非「想法」本身：原創性的表達（文章、音樂、圖畫、程式碼等）受著作權保護；純粹的想法、概念、事實資訊不受著作權保護。',
    source:'著作權法第1條；高中公民與社會教材' },
  { id:'law-copyright-3', subject:'law', concept:'intellectual-property', difficulty:2, version:QUESTION_VERSION,
    text:'未經著作權人同意，在社群媒體上分享他人照片，可能構成？',
    answers:['完全合法，網路上的東西都可以使用','侵害著作財產權（重製或公開傳輸）','只要標明來源就合法','只有商業用途才算侵權'],
    correct:1,
    explanation:'照片受著作權保護，未經著作人授權即在網路分享（公開傳輸），可能侵害著作財產權。即使標明來源，若無合理使用情形，仍可能構成侵權。',
    source:'著作權法第22條、第26條之1；高中公民與社會教材' },
  { id:'law-copyright-4', subject:'law', concept:'intellectual-property', difficulty:3, version:QUESTION_VERSION,
    text:'「合理使用」原則允許在哪些情況下使用他人著作而不構成侵權？',
    answers:['任何學術研究均可無限制使用','教育目的、評論、新聞報導等特定情形，且使用範圍合理','只要免費使用就算合理使用','著作超過10年就不需授權'],
    correct:1,
    explanation:'著作權法第65條規定合理使用原則，考量因素包括：使用目的（教育、評論、研究）、使用比例、對著作市場的影響等，符合者免責；但範圍需合理，不能全文轉載。',
    source:'著作權法第44條至第65條；高中公民與社會教材' },
  { id:'law-copyright-5', subject:'law', concept:'intellectual-property', difficulty:2, version:QUESTION_VERSION,
    text:'商標與著作權的主要區別是？',
    answers:['兩者完全相同，只是不同稱呼','商標須向主管機關申請註冊取得保護；著作權於創作完成時自動產生，無需申請','商標保護時間比著作權短','著作權保護的是商業標識'],
    correct:1,
    explanation:'著作權於創作完成時自動產生；商標須向智慧財產局申請審查核准後才受保護（商標法第2條）。兩者保護客體不同：著作權保護表達，商標保護識別商品或服務的標識。',
    source:'著作權法第10條；商標法第2條；高中公民與社會教材' },
  { id:'law-consumer-2', subject:'law', concept:'consumer-protection', difficulty:1, version:QUESTION_VERSION,
    text:'消費者保護法的主要保護對象是？',
    answers:['企業間的交易','消費者（非以商業目的購買商品或服務的個人）與企業間的交易','所有商業契約','政府採購行為'],
    correct:1,
    explanation:'消費者保護法保護「消費者」（非以商業目的購買商品或服務者）的權益，調整消費者與企業經營者間資訊不對等的問題，企業間交易不在保護範圍。',
    source:'消費者保護法第2條；高中公民與社會教材' },
  { id:'law-consumer-3', subject:'law', concept:'consumer-protection', difficulty:2, version:QUESTION_VERSION,
    text:'網路購物（通訊交易）依消費者保護法，消費者有幾天的猶豫期？',
    answers:['無猶豫期，商品拆封即不能退','7天內無條件退貨（猶豫期）','14天','30天'],
    correct:1,
    explanation:'消費者保護法第19條：通訊交易（如網路購物）消費者有7天猶豫期，可無條件退貨。例外情形（如易腐壞商品、客製化商品）則不在此限。',
    source:'消費者保護法第19條；高中公民與社會教材' },
  { id:'law-consumer-4', subject:'law', concept:'consumer-protection', difficulty:3, version:QUESTION_VERSION,
    text:'定型化契約中「顯失公平的條款」，依消費者保護法效力如何？',
    answers:['完全有效，雙方既已簽署就須遵守','無效；定型化契約條款違反平等互惠或顯失公平者不生效力','須經法院裁定才能主張無效','只有書面合約有此保護'],
    correct:1,
    explanation:'消費者保護法第12條：定型化契約中，違反誠信原則或對消費者顯失公平的條款，不構成契約內容（即無效）。消費者無須逐條審查才受保護。',
    source:'消費者保護法第11條、第12條；高中公民與社會教材' },
  { id:'law-consumer-5', subject:'law', concept:'consumer-protection', difficulty:2, version:QUESTION_VERSION,
    text:'消費者購買到瑕疵商品，可向哪些機構尋求協助？',
    answers:['只能直接去法院告','消費者保護官、消費者服務中心、消費爭議調解委員會，以及必要時提起民事訴訟','向刑事警察局報案','向財政部投訴'],
    correct:1,
    explanation:'消費爭議有多層次救濟：先向企業客服、再到消費者服務中心調解，或向縣市消費者保護官申訴，調解不成再提民事訴訟；消費者不必一開始就打官司。',
    source:'消費者保護法第42條以下；高中公民與社會教材' },
  { id:'law-agency-2', subject:'law', concept:'legal-representation', difficulty:1, version:QUESTION_VERSION,
    text:'未滿7歲的兒童（無行為能力人）所做的法律行為效力如何？',
    answers:['效力未定，須法定代理人承認','完全無效（民法第75條）','完全有效','只有財產行為無效'],
    correct:1,
    explanation:'民法第75條：無行為能力人（未滿7歲）之意思表示無效，其法律行為亦無效。相較之下，限制行為能力人（7歲以上未成年）所為行為則是效力未定。',
    source:'民法第75條；高中公民與社會教材' },
  { id:'law-agency-3', subject:'law', concept:'legal-representation', difficulty:2, version:QUESTION_VERSION,
    text:'父母對未成年子女的法定代理權，在哪種情況下會受限制或終止？',
    answers:['子女滿15歲即自動終止','子女滿18歲成年，或法院依法停止親權（如虐待）','父母離婚時自動終止','子女開始上班賺錢時'],
    correct:1,
    explanation:'法定代理終止於子女成年（滿18歲）；另，若父母有濫用親權行為（如虐待、疏忽），法院可依聲請停止或終止其親權，另行選定適當監護人。',
    source:'民法第1086條、第1090條；高中公民與社會教材' },
  { id:'law-agency-4', subject:'law', concept:'legal-representation', difficulty:3, version:QUESTION_VERSION,
    text:'委任代理（任意代理）與法定代理的最主要區別是？',
    answers:['兩者完全相同','法定代理源於法律直接規定（如父母對子女）；任意代理源於當事人授權','任意代理不需本人同意','法定代理只限於刑事程序'],
    correct:1,
    explanation:'法定代理由法律直接規定（親屬關係、監護關係），不需被代理人同意；任意代理（委任代理）是本人以授權行為賦予代理人代理權，基礎是本人的意思表示。',
    source:'民法第167條；高中公民與社會教材' },
  { id:'law-agency-5', subject:'law', concept:'legal-representation', difficulty:2, version:QUESTION_VERSION,
    text:'限制行為能力人（7至18歲）「日常生活所必需」的行為（如購買文具），法律如何處理？',
    answers:['一律無效，須事後追認','依民法第77條但書，純獲法律上利益或日常生活所必需者，有完全效力','須父母書面同意才有效','只能由父母代為辦理'],
    correct:1,
    explanation:'民法第77條但書規定：限制行為能力人所為純獲法律上利益或依其年齡及身分日常生活所必需，不需法定代理人同意，即有完全效力。',
    source:'民法第77條；高中公民與社會教材' },
  { id:'law-tort-2', subject:'law', concept:'tort-liability', difficulty:1, version:QUESTION_VERSION,
    text:'民法侵權行為的成立，除加害行為、損害及因果關係外，還需具備？',
    answers:['加害人須是公務員','加害人有故意或過失，且行為具不法性','損害金額須超過1萬元','須先經刑事判決確定'],
    correct:1,
    explanation:'民法第184條侵權行為要件：加害行為、有故意或過失（可歸責性）、不法性、損害結果、因果關係，缺一不可。',
    source:'民法第184條；高中公民與社會教材' },
  { id:'law-tort-3', subject:'law', concept:'tort-liability', difficulty:2, version:QUESTION_VERSION,
    text:'雇主對受僱人在執行職務中造成的損害，依民法負何種責任？',
    answers:['完全不負責任，由員工自行負責','連帶負損害賠償責任（民法第188條）','只負刑事責任','只有在雇主親自授意時才負責'],
    correct:1,
    explanation:'民法第188條：雇主對受僱人在執行職務中所加於第三人的損害，與受僱人連帶負賠償責任；除非雇主能證明已盡監督義務或縱加相當注意損害仍發生，才可免責。',
    source:'民法第188條；高中公民與社會教材' },
  { id:'law-tort-4', subject:'law', concept:'tort-liability', difficulty:3, version:QUESTION_VERSION,
    text:'商品製造人對其製造的商品所造成的消費者損害，依消費者保護法負何種責任？',
    answers:['僅限故意或過失才負責','無過失責任——只需證明商品有安全衛生上的危險且造成損害即可請求賠償','不負任何責任，由銷售商負責','由消費者舉證製造商的過失'],
    correct:1,
    explanation:'消費者保護法第7條規定企業經營者就其商品負「無過失責任」，消費者不須舉證製造商有無過失，只要證明商品有危險性且造成損害，即可請求賠償。',
    source:'消費者保護法第7條；高中公民與社會教材' },
  { id:'law-tort-5', subject:'law', concept:'tort-liability', difficulty:2, version:QUESTION_VERSION,
    text:'民事侵權的損害賠償範圍通常包含？',
    answers:['只有直接財產損失','積極損害（實際財產損失）、消極損害（預期利益損失），特定情況下亦包含慰撫金（非財產損害）','無限制，包含所有間接損失','只有精神損害'],
    correct:1,
    explanation:'損害賠償範圍：積極損害（醫療費、修繕費等實際損失）+ 消極損害（因此喪失的工作收入等預期利益）；涉及身體、健康、名譽等人格法益的損害，法律特別允許請求非財產損害（慰撫金）。',
    source:'民法第216條、第195條；高中公民與社會教材' },
  { id:'law-appeal-2', subject:'law', concept:'judicial-remedy', difficulty:1, version:QUESTION_VERSION,
    text:'台灣的審級制度為何？',
    answers:['一審終結，不得上訴','三級三審：地方法院→高等法院→最高法院','兩級兩審','四級四審'],
    correct:1,
    explanation:'我國採三級三審制：第一審地方法院、第二審高等法院（上訴審）、第三審最高法院（法律審）；但部分案件（如輕罪）可能只有二審，或第三審採許可制。',
    source:'法院組織法；刑事訴訟法；高中公民與社會教材' },
  { id:'law-appeal-3', subject:'law', concept:'judicial-remedy', difficulty:2, version:QUESTION_VERSION,
    text:'第三審（最高法院）主要審查哪些問題？',
    answers:['全面重新調查事實與證據','主要審查法律適用是否正確（法律審），原則上不再調查事實','審查被告是否認罪','主要調查新的事證'],
    correct:1,
    explanation:'最高法院是法律審，主要審查下級法院對法律的解釋與適用是否正確，原則上不再調查事實（事實認定已在一、二審終結），目的是統一法律見解。',
    source:'刑事訴訟法第377條；民事訴訟法第467條；高中公民與社會教材' },
  { id:'law-appeal-4', subject:'law', concept:'judicial-remedy', difficulty:3, version:QUESTION_VERSION,
    text:'非常上訴是用來救濟哪種情形？',
    answers:['一般對判決不服的救濟','已確定判決發現有違法情形，由檢察總長向最高法院提起','未成年人的特別救濟途徑','對行政機關處分不服的救濟'],
    correct:1,
    explanation:'非常上訴是針對已確定之裁判，若發現其違背法令，由最高檢察署檢察總長向最高法院提起，是確定判決的非常救濟途徑，旨在統一法令適用。',
    source:'刑事訴訟法第441條；高中公民與社會教材' },
  { id:'law-appeal-5', subject:'law', concept:'judicial-remedy', difficulty:2, version:QUESTION_VERSION,
    text:'再審（刑事再審）的主要適用情形是？',
    answers:['任何對判決不服均可申請','確定判決後，發現有新事證或原判決有重大違法，可聲請再審以重新審理','只有無罪判決可聲請再審','由法官主動發動'],
    correct:1,
    explanation:'再審是已確定判決的特別救濟：有證明原判決認定事實錯誤的新事證（如DNA鑑定），可聲請再審。刑事再審可為受判決人利益（如冤獄平反）提起。',
    source:'刑事訴訟法第420條；高中公民與社會教材' },
  // ── 公民補充題 ────────────────────────────────────────────
  { id:'civics-rights-2', subject:'civics', concept:'fundamental-rights', difficulty:2, version:QUESTION_VERSION,
    text:'憲法保障的基本人權中，「平等權」的意義是？',
    answers:['所有人在任何情況下都必須獲得完全相同的待遇','法律上不得因種族、性別、宗教、黨派等做非合理的差別待遇','只有公民才有平等權','只限於政治領域的平等'],
    correct:1,
    explanation:'憲法第7條平等原則：禁止「恣意差別」（非基於合理事由的不同對待）；但合理分類（如依年齡決定選舉資格）是允許的，並非要求齊頭式的形式平等。',
    source:'中華民國憲法第7條；司法院大法官解釋；高中公民與社會教材' },
  { id:'civics-rights-3', subject:'civics', concept:'fundamental-rights', difficulty:1, version:QUESTION_VERSION,
    text:'依憲法第11條，言論自由的保障範圍包含？',
    answers:['只有政治性言論','各種言論的表達自由，包括政治、學術、藝術、商業等，但不包括造謠毀謗等','任何言論均受絕對保護','只有書面言論'],
    correct:1,
    explanation:'言論自由保障範圍廣泛，包含各式言論；但非絕對——誹謗、煽動、妨害公益等言論，法律可予以限制，限制須符合比例原則且有法律依據。',
    source:'中華民國憲法第11條；司法院大法官解釋；高中公民與社會教材' },
  { id:'civics-rights-4', subject:'civics', concept:'fundamental-rights', difficulty:3, version:QUESTION_VERSION,
    text:'基本人權可以被限制嗎？若可以，須符合什麼條件？',
    answers:['不可以，基本人權是絕對的','可以，但須有法律依據且符合比例原則（憲法第23條）','只要多數人同意即可限制','由行政機關自行決定是否限制'],
    correct:1,
    explanation:'憲法第23條：人民的自由與權利，除防止妨礙他人自由、避免緊急危難、維持社會秩序、增進公共利益外，不得以法律限制；且限制手段須符合比例原則（必要且相稱）。',
    source:'中華民國憲法第23條；高中公民與社會教材' },
  { id:'civics-rights-5', subject:'civics', concept:'fundamental-rights', difficulty:2, version:QUESTION_VERSION,
    text:'憲法保障的「工作權」是指？',
    answers:['政府必須替所有人提供工作機會','人民選擇職業的自由，以及從事工作不受不合理干涉的權利','只限於公務員的就業保障','私人企業的工作規則不受憲法限制'],
    correct:1,
    explanation:'憲法第15條工作權保障人民選擇職業及從事工作的自由，包括職業選擇自由和執行自由；政府的干預須有正當理由且符合比例原則。',
    source:'中華民國憲法第15條；司法院大法官解釋；高中公民與社會教材' },
  { id:'civics-due-process-2', subject:'civics', concept:'due-process', difficulty:1, version:QUESTION_VERSION,
    text:'「正當法律程序」在刑事訴訟中，最基本的體現是？',
    answers:['被告有義務配合所有調查','被告有受告知、聽審及法律協助的權利（如告知罪名、有辯護人協助）','法院可以不通知被告直接判決','只要結果公平就不需要程序保障'],
    correct:1,
    explanation:'正當程序在刑事訴訟中包含：被告有權知道指控內容（告知）、有機會陳述與答辯（聽審）、有辯護人協助（法律協助）等，確保程序公平。',
    source:'中華民國憲法第8條；刑事訴訟法；高中公民與社會教材' },
  { id:'civics-due-process-3', subject:'civics', concept:'due-process', difficulty:2, version:QUESTION_VERSION,
    text:'行政機關對人民做出不利處分（如罰鍰）前，通常需要做什麼？',
    answers:['直接執行，事後告知即可','給予當事人陳述意見的機會（聽證或陳述機會），否則違反正當程序','通報立法院審議','由法院先行裁定'],
    correct:1,
    explanation:'行政程序法規定，行政機關作成不利處分前，應給予當事人陳述意見的機會（聽證、通知陳述等），否則程序違法，當事人可主張撤銷。',
    source:'行政程序法第102條；高中公民與社會教材' },
  { id:'civics-due-process-4', subject:'civics', concept:'due-process', difficulty:3, version:QUESTION_VERSION,
    text:'「比例原則」在正當程序中的作用是？',
    answers:['要求所有案件一律用最嚴重的手段','限制手段應與目的間保持合理比例，不得超過達成目的所必要的程度','只適用於刑事案件','要求手段必須最便宜'],
    correct:1,
    explanation:'比例原則（適當性、必要性、相稱性）：國家限制人民權利的手段，須能達成正當目的（適當性）、是造成最小損害的手段（必要性）、且限制強度與公共利益相稱（相稱性）。',
    source:'中華民國憲法第23條；行政程序法第7條；高中公民與社會教材' },
  { id:'civics-due-process-5', subject:'civics', concept:'due-process', difficulty:2, version:QUESTION_VERSION,
    text:'「法律保留原則」是指？',
    answers:['法律只能由法院解釋','對人民的重要事項限制，必須有法律（立法院通過）作為依據，行政機關不能自行創設限制','政府可以保留某些法律不公開','只有稅收需要法律依據'],
    correct:1,
    explanation:'法律保留原則（憲法第23條）：限制人民自由權利的重要措施，必須由立法院制定法律為依據，行政機關不能以命令或行政規則任意限制人民權利。',
    source:'中華民國憲法第23條；高中公民與社會教材' },
  { id:'civics-separation-2', subject:'civics', concept:'separation-of-powers', difficulty:1, version:QUESTION_VERSION,
    text:'依中華民國憲法，立法院的主要職權是？',
    answers:['執行法律、推動政策','制定法律、審查預算、監督行政','解釋憲法與法律','管轄訴訟案件'],
    correct:1,
    explanation:'立法院是代議機構，主要職權包括：制定、修改或廢止法律、審查政府總預算、對行政院提出不信任案、監督行政等，反映人民對政府的授權與監督。',
    source:'中華民國憲法第62條至第73條；高中公民與社會教材' },
  { id:'civics-separation-3', subject:'civics', concept:'separation-of-powers', difficulty:2, version:QUESTION_VERSION,
    text:'司法院大法官的主要職責是？',
    answers:['偵查犯罪','解釋憲法、統一解釋法令、審理政黨違憲','制定法律','管理全國法院行政'],
    correct:1,
    explanation:'司法院大法官主要負責解釋憲法（審查法律或行為是否違憲）、統一解釋法令、審理總統副總統彈劾案及政黨違憲解散案，是憲政秩序的守護者。',
    source:'中華民國憲法第78條；司法院組織法；高中公民與社會教材' },
  { id:'civics-separation-4', subject:'civics', concept:'separation-of-powers', difficulty:3, version:QUESTION_VERSION,
    text:'中華民國憲法的「五權分立」與西方「三權分立」的主要差異是？',
    answers:['完全相同，只是名稱不同','增加考試院（主管公務員考選）與監察院（彈劾、審計），形成五院制','考試院負責刑事訴追','監察院制定法律'],
    correct:1,
    explanation:'孫中山先生主張在立法、行政、司法三權外，再加上考試權（避免用人唯親）和監察權（彈劾官員），形成五院體制，考試院負責公務員考選，監察院負責彈劾與審計。',
    source:'中華民國憲法第83條、第90條；高中公民與社會教材' },
  { id:'civics-separation-5', subject:'civics', concept:'separation-of-powers', difficulty:2, version:QUESTION_VERSION,
    text:'立法院通過的法律，行政院認為窒礙難行時，可以怎麼做？',
    answers:['直接拒絕公布，不需任何程序','移請立法院覆議；覆議未通過，行政院院長應辭職或接受','由總統直接宣布法律無效','向大法官申請解釋憲法停止施行'],
    correct:1,
    explanation:'憲法增修條文規定：行政院對立法院決議之法律案若認為窒礙難行，經總統核可，可移請立法院覆議；覆議時若立法院堅持原議，行政院長應接受或辭職。',
    source:'中華民國憲法增修條文第3條；高中公民與社會教材' },
  { id:'civics-election-2', subject:'civics', concept:'election-system', difficulty:1, version:QUESTION_VERSION,
    text:'台灣現行選舉的普通選舉原則是指？',
    answers:['只有有土地的人才能投票','凡年滿18歲（2022年修憲後）的中華民國國民均有選舉權','只有受高等教育者才能投票','投票依財富多寡決定票數'],
    correct:1,
    explanation:'普通選舉（普選）原則：選舉資格只以基本身分（國籍+年齡）為要件，不依性別、財產、教育等差別，確保廣泛的政治參與。',
    source:'公職人員選舉罷免法；中華民國憲法；高中公民與社會教材' },
  { id:'civics-election-3', subject:'civics', concept:'election-system', difficulty:2, version:QUESTION_VERSION,
    text:'總統選舉採用哪種制度？',
    answers:['兩輪投票制（決選制）','相對多數一輪投票制（得票最多者當選，無需過半）','國會間接選舉','由各政黨按席次比例推選'],
    correct:1,
    explanation:'台灣總統選舉採「相對多數制」（first-past-the-post）：得票最多者即當選，不需過半數，也沒有第二輪決選。此制度有利大黨，但可能造成多數候選人互相分票。',
    source:'總統副總統選舉罷免法；高中公民與社會教材' },
  { id:'civics-election-4', subject:'civics', concept:'election-system', difficulty:3, version:QUESTION_VERSION,
    text:'公民投票（公投）與選舉的主要差異是？',
    answers:['兩者完全相同','公投是人民直接針對政策議題表決，選舉是選出代表人；兩者分屬直接民主與代議民主的工具','公投只能在選舉時同時舉行','公投結果政府可以不理會'],
    correct:1,
    explanation:'選舉是選出代表人（代議民主）；公投是人民直接對特定政策或法律議題表決（直接民主）。台灣公投法規定公投通過需符合特定門檻，且其效力視議題性質而定。',
    source:'公民投票法；高中公民與社會教材' },
  { id:'civics-election-5', subject:'civics', concept:'election-system', difficulty:2, version:QUESTION_VERSION,
    text:'罷免制度的主要目的是？',
    answers:['讓政黨可以撤換不聽話的民代','由選民直接撤換不符期待的民選公職人員，是選舉之外的課責機制','讓法院裁決不適任的官員','作為行政機關懲處官員的工具'],
    correct:1,
    explanation:'罷免制度允許選民在任期中，透過連署和投票的方式將民選公職人員撤換，是選舉課責以外的補充機制，防止民代長期脫離民意而無法問責。',
    source:'公職人員選舉罷免法；高中公民與社會教材' },
  { id:'civics-local-2', subject:'civics', concept:'local-autonomy', difficulty:1, version:QUESTION_VERSION,
    text:'縣市政府施政須符合哪個原則？',
    answers:['完全自主，不受任何上級規範','依地方制度法，地方自治事項須在憲法和法律框架下進行，不得違反中央法規','由直轄市市長單獨決定','中央政府無權干預任何地方事務'],
    correct:1,
    explanation:'地方自治實行「均權制度」（憲法第111條），地方自治事項在法律框架下自理，但不得違反中央法規；中央與地方事權劃分依事務性質而定。',
    source:'地方制度法；中華民國憲法第111條；高中公民與社會教材' },
  { id:'civics-local-3', subject:'civics', concept:'local-autonomy', difficulty:2, version:QUESTION_VERSION,
    text:'地方議會（縣市議會）的主要職能是？',
    answers:['執行縣市政府的行政命令','審議地方預算、制定自治條例、監督縣市政府（行政）','向中央請求補助','管理地方警察'],
    correct:1,
    explanation:'地方議會是地方立法機關，主要職能：審查通過地方年度預算、制定與廢止自治條例（地方法規）、對縣市政府的施政進行監督與質詢，以代表居民監督行政。',
    source:'地方制度法第35條；高中公民與社會教材' },
  { id:'civics-local-4', subject:'civics', concept:'local-autonomy', difficulty:3, version:QUESTION_VERSION,
    text:'地方政府制定的「自治條例」，若與中央法律牴觸，其效力如何？',
    answers:['地方條例優先，因更貼近在地需求','牴觸上位法（中央法律或憲法）者無效，地方法規不得牴觸中央法律','由地方議會自行決定','需由總統裁奪'],
    correct:1,
    explanation:'地方制度法第30條：自治條例不得牴觸憲法、法律及中央法規命令；牴觸者無效。此體現「上位法優先」原則，確保法律秩序的一致性。',
    source:'地方制度法第30條；高中公民與社會教材' },
  { id:'civics-local-5', subject:'civics', concept:'local-autonomy', difficulty:2, version:QUESTION_VERSION,
    text:'台灣地方行政的層級由上到下依序為？',
    answers:['鄉鎮→縣→省→中央','中央→直轄市或縣市→鄉鎮市區→村里','中央→省→縣→鄉鎮','直轄市→縣市→中央'],
    correct:1,
    explanation:'台灣自1998年凍省後實行「精省」，地方行政層級為：中央→直轄市（六都）或縣市→鄉鎮市區→村里，省政府功能已大幅縮減，實際運作為二到三級制。',
    source:'地方制度法；高中公民與社會教材' },
  { id:'civics-remedy-2', subject:'civics', concept:'administrative-remedy', difficulty:1, version:QUESTION_VERSION,
    text:'訴願的管轄機關通常是？',
    answers:['與作成原處分的相同機關','原處分機關的上級機關','地方法院','立法院'],
    correct:1,
    explanation:'訴願法規定：訴願由原處分的上級機關管轄（中央部會的上級是行政院；縣市政府的上級是各該部會）；不服訴願決定再提行政訴訟。',
    source:'訴願法第4條；高中公民與社會教材' },
  { id:'civics-remedy-3', subject:'civics', concept:'administrative-remedy', difficulty:2, version:QUESTION_VERSION,
    text:'行政訴訟的審理機構是？',
    answers:['普通法院（地方法院、高等法院）','行政法院（高等行政法院及最高行政法院）','監察院','立法院'],
    correct:1,
    explanation:'行政爭訟（行政機關違法或不當處分的救濟）由行政法院審理；普通法院（地院、高院、最高法院）審理民刑事訴訟。兩者是不同的審判體系。',
    source:'行政訴訟法；行政法院組織法；高中公民與社會教材' },
  { id:'civics-remedy-4', subject:'civics', concept:'administrative-remedy', difficulty:3, version:QUESTION_VERSION,
    text:'行政機關的處分若侵害人民權利，人民除行政救濟外，還可向哪個機構反映？',
    answers:['只能透過行政救濟（訴願和行政訴訟）','監察院（向監察委員陳情，監察院可調查行政機關違失）或向民意代表陳情','向最高法院申訴','向警察局舉報'],
    correct:1,
    explanation:'除訴願和行政訴訟外，人民可向監察院陳情（監察院有彈劾、糾舉、糾正行政機關的權力）、向民意代表反映，形成多元課責。',
    source:'監察法；高中公民與社會教材' },
  { id:'civics-remedy-5', subject:'civics', concept:'administrative-remedy', difficulty:2, version:QUESTION_VERSION,
    text:'行政機關的行政處分「違法」與「不當」有何區別？',
    answers:['兩者完全相同，都是指違反法律','違法是指違反法律或法規命令；不當是指雖合法但不合理或不妥適（如過度處罰）','只有違法才能申訴，不當不能救濟','不當比違法更嚴重'],
    correct:1,
    explanation:'違法處分違反法律規定；不當處分雖在法定範圍內，但裁量不合理。訴願可救濟違法及不當；行政訴訟原則上只救濟違法。',
    source:'訴願法第1條；行政訴訟法；高中公民與社會教材' },
  { id:'civics-media-2', subject:'civics', concept:'media-literacy', difficulty:1, version:QUESTION_VERSION,
    text:'「假新聞」（disinformation）的主要特徵是？',
    answers:['內容誇張但不影響決策','刻意捏造或扭曲的不實資訊，目的在欺騙閱聽人或影響輿論','報導立場偏頗但內容屬實','只出現在網路媒體'],
    correct:1,
    explanation:'假新聞（disinformation）特指有意傳播的不實訊息，與錯誤資訊（misinformation，無意識傳播的錯誤）不同；其目的通常是欺騙、操控輿論或製造社會分裂。',
    source:'高中公民與社會教材；媒體素養教育課程綱要' },
  { id:'civics-media-3', subject:'civics', concept:'media-literacy', difficulty:2, version:QUESTION_VERSION,
    text:'看到聳動的新聞標題，媒體素養良好的人會？',
    answers:['立即分享給朋友，增加傳播速度','查看來源可信度、尋找其他報導的佐證、核實內容後再判斷','只相信自己習慣的媒體','相信文章中引用的數字一定是真的'],
    correct:1,
    explanation:'媒體素養的實踐：遇到聳動標題先「暫停分享」，查核資訊來源（官方、學術、多方媒體），確認是否有其他報導佐證，辨別是否為標題黨或情緒操弄，再決定是否相信或轉傳。',
    source:'高中公民與社會教材；媒體素養教育課程綱要' },
  { id:'civics-media-4', subject:'civics', concept:'media-literacy', difficulty:3, version:QUESTION_VERSION,
    text:'「同溫層效應」（echo chamber）對民主政治的潛在危害是？',
    answers:['讓更多人參與政治討論','使人只接觸與自己立場相同的資訊，降低理解多元觀點的能力，可能加劇社會分化','讓選舉更公平','促進媒體多元發展'],
    correct:1,
    explanation:'同溫層效應：演算法強化選擇性接觸，使人愈來愈只看符合自己既有立場的資訊，導致立場固化、無法理解他人觀點，在民主政治中可能造成對話困難和社會極化。',
    source:'高中公民與社會教材；媒體素養教育課程綱要' },
  { id:'civics-media-5', subject:'civics', concept:'media-literacy', difficulty:2, version:QUESTION_VERSION,
    text:'在台灣，新聞媒體的所有權結構為何對新聞報導有影響？',
    answers:['完全無影響，記者都是公正的','媒體所有者的利益可能影響報導立場，閱聽人應了解媒體背景','政府保證所有媒體都公正報導','台灣所有媒體都是國有的'],
    correct:1,
    explanation:'媒體素養強調了解媒體所有權：不同財團或政治力量擁有媒體可能影響其報導角度，閱聽人應主動了解媒體背景，並比較多元來源，避免接受單一視角。',
    source:'高中公民與社會教材；媒體素養教育課程綱要' },
  { id:'civics-ngo-2', subject:'civics', concept:'civil-society', difficulty:1, version:QUESTION_VERSION,
    text:'公民社會的功能之一是？',
    answers:['完全取代政府的職能','作為政府與市場之外的第三部門，提供服務、倡議公共議題並監督政府','只是人民休閒娛樂的場所','只在選舉時才發揮作用'],
    correct:1,
    explanation:'公民社會（第三部門）在政府和市場之外，透過NGO、社區組織、倡議團體等，彌補政府和市場的不足，提供服務、表達多元利益、監督公共權力，是民主社會重要的組成部分。',
    source:'高中公民與社會教材；聯合國相關文件' },
  { id:'civics-ngo-3', subject:'civics', concept:'civil-society', difficulty:2, version:QUESTION_VERSION,
    text:'公民參與公共事務的方式，除了選舉投票外，還包括？',
    answers:['只能等待選舉','連署請願、遊行示威、參與公聽會、社區組織、消費者行動等多元形式','只能透過媒體施壓','加入政黨是唯一合法途徑'],
    correct:1,
    explanation:'民主參與不限於投票：連署、請願、集會遊行（依法）、參與公聽會或審議民主機制、加入倡議團體、消費者運動等，都是公民在選舉外影響公共決策的合法途徑。',
    source:'高中公民與社會教材' },
  { id:'civics-ngo-4', subject:'civics', concept:'civil-society', difficulty:3, version:QUESTION_VERSION,
    text:'「審議式民主」（deliberative democracy）的核心精神是？',
    answers:['只有專家才能參與政策討論','強調在充分資訊和理性對話的基礎上，由公民共同討論形成公共意見，而非純粹多數決','多數決定一切','由政府替公民做決定'],
    correct:1,
    explanation:'審議式民主強調：決策前應給予公民充分資訊、創造理性對話空間（如公民會議、審議論壇），讓不同立場的人透過理性說理相互理解後再決定，追求討論品質而非單純計票。',
    source:'高中公民與社會教材；哈伯馬斯審議民主理論' },
  { id:'civics-ngo-5', subject:'civics', concept:'civil-society', difficulty:2, version:QUESTION_VERSION,
    text:'台灣非政府組織（NGO）的特徵之一是？',
    answers:['必須由政府機關監管才能運作','依人民團體法或財團法人法登記，獨立運作，不以營利為目的','所有成員必須是志工，不得支薪','不能參與任何政治議題倡議'],
    correct:1,
    explanation:'台灣NGO依法（如人民團體法、財團法人法）登記成立，獨立於政府之外；非營利不代表不能有員工薪資（可支付合理薪資），但盈餘不得分配給成員，必須用於組織宗旨。',
    source:'人民團體法；財團法人法；高中公民與社會教材' },
  // ── 經濟補充題 ────────────────────────────────────────────
  { id:'econ-supply-demand-2', subject:'economics', concept:'supply-demand', difficulty:1, version:QUESTION_VERSION,
    text:'均衡價格是如何決定的？',
    answers:['由政府訂定','由供給與需求共同決定——供需相等之處即為均衡','只由生產成本決定','由消費者集體協議決定'],
    correct:1,
    explanation:'市場均衡：當供給量等於需求量時，市場達到均衡，此時的價格稱為均衡價格，數量稱為均衡數量。市場會自動向均衡調整（超額供給→降價；超額需求→漲價）。',
    source:'高中經濟學教材；供需均衡分析' },
  { id:'econ-supply-demand-3', subject:'economics', concept:'supply-demand', difficulty:2, version:QUESTION_VERSION,
    text:'當某商品生產技術進步，生產成本大幅降低，供給曲線會如何移動？',
    answers:['向左移動（供給減少）','向右移動（供給增加）','不移動，只有價格改變','需求曲線向右移動'],
    correct:1,
    explanation:'技術進步降低生產成本，在相同價格下廠商願意生產更多，供給增加；供給曲線向右移動，在需求不變下均衡價格下降、均衡數量增加。',
    source:'高中經濟學教材；供需均衡分析' },
  { id:'econ-supply-demand-4', subject:'economics', concept:'supply-demand', difficulty:3, version:QUESTION_VERSION,
    text:'政府對某商品訂定「價格上限」（低於均衡價），通常會產生什麼後果？',
    answers:['自動達到供需平衡','供給量減少而需求量增加，出現「超額需求」（短缺）','價格繼續上漲超過上限','只影響廠商，不影響消費者'],
    correct:1,
    explanation:'價格上限低於均衡價時，廠商降低供給，消費者增加需求，導致超額需求（需求量>供給量），市場出現短缺（如管制租金導致房屋供不應求）。',
    source:'高中經濟學教材；價格管制分析' },
  { id:'econ-supply-demand-5', subject:'economics', concept:'supply-demand', difficulty:2, version:QUESTION_VERSION,
    text:'互補品（如汽車和汽油）的需求關係是？',
    answers:['互相競爭，一個漲價另一個需求增加','一起使用的商品：若汽車價格大漲，汽油需求通常也會下降','彼此完全獨立，互不影響','汽油漲價會使汽車需求增加'],
    correct:1,
    explanation:'互補品是需要一起使用的商品：若汽車大幅漲價，消費者少買車，汽油需求也隨之下降，兩者需求呈正相關。替代品（如奶油與乳瑪琳）一個漲價會使另一個需求上升。',
    source:'高中經濟學教材；需求的影響因素' },
  { id:'econ-opportunity-cost-2', subject:'economics', concept:'opportunity-cost', difficulty:1, version:QUESTION_VERSION,
    text:'機會成本的定義是？',
    answers:['做一件事情所花費的金錢總額','做某一選擇時，所必須放棄的次佳選擇之價值','所有可能選擇的加總成本','政府徵收的機會稅'],
    correct:1,
    explanation:'機會成本是做出某選擇時，因而放棄的「次佳替代選擇」的價值，而非所有放棄選項的總和。它是經濟決策的核心概念，幫助衡量選擇的真實成本。',
    source:'高中經濟學教材；機會成本概念' },
  { id:'econ-opportunity-cost-3', subject:'economics', concept:'opportunity-cost', difficulty:2, version:QUESTION_VERSION,
    text:'一家公司使用自有土地作為停車場而非出租，此自有土地的機會成本是？',
    answers:['零，因為是自己的土地不需付租金','放棄出租所能獲得的租金收入','土地的市場購買價格','建造停車場的工程費用'],
    correct:1,
    explanation:'機會成本包含「隱性成本」：即使用自己的資源，也有機會成本——放棄出租所能獲得的租金。企業真正的「經濟利潤」須扣除所有機會成本（包括隱性成本）。',
    source:'高中經濟學教材；機會成本與隱性成本' },
  { id:'econ-opportunity-cost-4', subject:'economics', concept:'opportunity-cost', difficulty:3, version:QUESTION_VERSION,
    text:'政府用10億元興建體育館，其機會成本是？',
    answers:['體育館的建設成本10億元本身','這10億元若用於其他最有價值的用途所能獲得的效益（如醫療或教育）','以後體育館的維護費','場館開幕後的門票收入'],
    correct:1,
    explanation:'公共資源有限，政府花費10億蓋體育館的機會成本，是同樣這10億若用於其他最佳替代用途（如醫院、學校）所能產生的效益；公共政策評估必須納入機會成本考量。',
    source:'高中經濟學教材；公共支出與機會成本' },
  { id:'econ-opportunity-cost-5', subject:'economics', concept:'opportunity-cost', difficulty:2, version:QUESTION_VERSION,
    text:'大學畢業生選擇繼續讀研究所而非就業，讀研究所的機會成本包含？',
    answers:['只有學費','學費加上在就業市場損失的工資收入（隱性成本）','只有放棄的工資','只有精神壓力'],
    correct:1,
    explanation:'讀研究所的機會成本 = 顯性成本（學費、生活費等直接支出）+ 隱性成本（若去工作本可獲得的薪資）。完整的機會成本分析包含兩者。',
    source:'高中經濟學教材；機會成本分析' },
  { id:'econ-externality-2', subject:'economics', concept:'market-failure', difficulty:1, version:QUESTION_VERSION,
    text:'下列哪個是「正外部性」（正外部效益）的例子？',
    answers:['工廠排放廢氣污染空氣','接種疫苗：個人接種可降低整體傳染風險，使未接種者也受益','塞車消耗大量燃料','噪音污染影響鄰居'],
    correct:1,
    explanation:'正外部性是指行為帶給未參與交易的第三者的正面效益：接種疫苗不僅保護自己，也降低病毒傳播，使他人受益。社會期望的正外部性產品通常供給不足，需政府補貼。',
    source:'高中經濟學教材；外部性與市場失靈' },
  { id:'econ-externality-3', subject:'economics', concept:'market-failure', difficulty:2, version:QUESTION_VERSION,
    text:'「公共財」的主要特性是？',
    answers:['只有政府可以提供','非排他性（無法排除未付費者享用）和非競爭性（一人使用不減少他人可用量）','由所有人共同出資購買','效益只限於付費者'],
    correct:1,
    explanation:'公共財具有：非排他性（不能排除未付費者，如路燈、國防）和非競爭性（一人使用不影響他人使用量）。因「搭便車問題」，市場傾向低估供給，需政府介入。',
    source:'高中經濟學教材；公共財與市場失靈' },
  { id:'econ-externality-4', subject:'economics', concept:'market-failure', difficulty:3, version:QUESTION_VERSION,
    text:'政府對「負外部成本」的矯正手段，通常包含？',
    answers:['補貼生產廠商','課徵稅（庇古稅）或設立排放許可交易，使外部成本內部化','放任市場自行解決','補貼受害者'],
    correct:1,
    explanation:'庇古稅（Pigouvian Tax）：對產生負外部成本的活動課稅，迫使生產者將外部成本納入價格（內部化），減少生產；或設立碳交易等市場機制，兩者皆可矯正市場失靈。',
    source:'高中經濟學教材；外部性矯正政策' },
  { id:'econ-externality-5', subject:'economics', concept:'market-failure', difficulty:2, version:QUESTION_VERSION,
    text:'「資訊不對稱」是一種市場失靈，下列哪個例子最能說明？',
    answers:['兩家公司商量定價','二手車市場中，賣方知道車子的真實狀況，買方不知，可能導致逆選擇','所有商品都訂了價格','政府管制導致供給不足'],
    correct:1,
    explanation:'資訊不對稱（Akerlof的「檸檬問題」）：二手車賣方了解車況，買方不了解，買方為了防範買到壞車，只願以低價購買，使優質二手車市場萎縮，出現「逆選擇」。',
    source:'高中經濟學教材；Akerlof檸檬市場理論' },
  { id:'econ-gdp-2', subject:'economics', concept:'gdp-growth', difficulty:1, version:QUESTION_VERSION,
    text:'下列何者不計入GDP的計算？',
    answers:['台灣工廠在台灣境內生產的汽車','台灣人在美國投資的股票股息','外資在台灣設廠的產值','台灣人在台灣境內購買的服務'],
    correct:1,
    explanation:'GDP 計算的是「一國境內」的生產，不論生產者國籍。台灣人在海外獲得的股息屬於GNP（國民生產毛額）的範疇，不計入GDP；外資在台灣的產值則計入台灣GDP。',
    source:'高中經濟學教材；行政院主計總處' },
  { id:'econ-gdp-3', subject:'economics', concept:'gdp-growth', difficulty:2, version:QUESTION_VERSION,
    text:'「實質GDP」和「名目GDP」的差別是？',
    answers:['完全相同，只是叫法不同','名目GDP以當年市場價格計算；實質GDP扣除通膨後以固定基期價格計算，更能反映真實產出變化','實質GDP包含地下經濟','名目GDP已調整為購買力平價'],
    correct:1,
    explanation:'名目GDP以當期市場價格衡量，受物價波動影響；實質GDP以固定基期價格衡量，排除通膨影響，能真正反映產出數量的變化。比較不同年度的成長，應用實質GDP。',
    source:'高中經濟學教材；行政院主計總處統計說明' },
  { id:'econ-gdp-4', subject:'economics', concept:'gdp-growth', difficulty:3, version:QUESTION_VERSION,
    text:'GDP無法衡量的面向包含？',
    answers:['農業生產總值','人民的生活品質、環境品質、所得分配公平性','政府的稅收','私人消費支出'],
    correct:1,
    explanation:'GDP 的侷限：無法衡量所得分配（GDP高但不均等）、環境永續性（GDP增長可能伴隨環境破壞）、非市場活動（家庭照顧、志工）、主觀幸福感等，近年提倡以人類發展指數等補充指標。',
    source:'高中經濟學教材；聯合國人類發展報告' },
  { id:'econ-gdp-5', subject:'economics', concept:'gdp-growth', difficulty:2, version:QUESTION_VERSION,
    text:'GDP計算方式中，「支出法」的公式是？',
    answers:['GDP = 工資 + 利潤 + 利息 + 地租','GDP = 民間消費(C) + 政府支出(G) + 投資(I) + 淨出口(X-M)','GDP = 總產值 − 中間投入','GDP = 人口 × 平均所得'],
    correct:1,
    explanation:'支出法GDP：C（民間消費）+ I（私人投資）+ G（政府支出）+ (X-M)（出口減進口的淨出口），是最常用的GDP計算角度，代表一國境內對最終產品的總需求。',
    source:'高中經濟學教材；行政院主計總處' },
  { id:'econ-inflation-2', subject:'economics', concept:'inflation-deflation', difficulty:1, version:QUESTION_VERSION,
    text:'通貨緊縮（deflation）對經濟可能造成哪種危害？',
    answers:['使貨幣購買力下降','消費者預期物價繼續下跌而延遲消費，導致需求減少、生產萎縮、失業增加（通縮螺旋）','促進投資和消費','使政府稅收增加'],
    correct:1,
    explanation:'通縮的危害：物價持續下跌→消費者推遲購買→廠商銷售下滑→減產裁員→收入下降→消費再萎縮，形成通縮螺旋。日本1990年代「失落的十年」是經典案例。',
    source:'高中經濟學教材；貨幣政策與物價穩定' },
  { id:'econ-inflation-3', subject:'economics', concept:'inflation-deflation', difficulty:2, version:QUESTION_VERSION,
    text:'衡量一般物價水準變動的指標，最常用的是？',
    answers:['股票市場指數','消費者物價指數（CPI）','台灣加權指數','不動產成交量'],
    correct:1,
    explanation:'消費者物價指數（CPI）追蹤代表性的消費商品與服務籃子的價格變動，是衡量通貨膨脹（或緊縮）最廣泛使用的指標；台灣CPI由行政院主計總處定期發布。',
    source:'高中經濟學教材；行政院主計總處CPI說明' },
  { id:'econ-inflation-4', subject:'economics', concept:'inflation-deflation', difficulty:3, version:QUESTION_VERSION,
    text:'「惡性通膨」（hyperinflation）的主要成因之一是？',
    answers:['利率過高使人不願消費','政府大量印鈔以支付財政赤字，造成貨幣大量流通而急速貶值','外資大量流入','商品過度生產'],
    correct:1,
    explanation:'惡性通膨多因政府過度發行貨幣（印鈔）以應付財政赤字，貨幣供給遠超過實際產出，貨幣迅速貶值，物價可能每天翻倍。歷史案例：1920年代德國、近年委內瑞拉。',
    source:'高中經濟學教材；貨幣數量理論' },
  { id:'econ-inflation-5', subject:'economics', concept:'inflation-deflation', difficulty:2, version:QUESTION_VERSION,
    text:'「通貨膨脹」的成因，哪種類型是「需求拉動型」？',
    answers:['原油價格大漲推高生產成本','景氣過熱，消費者和企業需求大增超過產能，拉動物價上漲','薪資快速上漲增加生產成本','匯率貶值使進口物價上漲'],
    correct:1,
    explanation:'通膨成因分類：需求拉動（demand-pull）——總需求過旺超過產能；成本推動（cost-push）——生產成本上升（如油價）推高物價。兩者應對政策不同。',
    source:'高中經濟學教材；總體經濟學' },
  { id:'econ-monetary-2', subject:'economics', concept:'monetary-policy', difficulty:1, version:QUESTION_VERSION,
    text:'台灣的貨幣政策主要由哪個機構負責？',
    answers:['財政部','中華民國中央銀行','行政院主計總處','金融監督管理委員會'],
    correct:1,
    explanation:'台灣中央銀行負責貨幣政策，包括訂定利率（重貼現率）、公開市場操作（買賣政府公債調節貨幣供給）、存款準備率等工具，以維持物價穩定和金融秩序。',
    source:'高中經濟學教材；中央銀行法' },
  { id:'econ-monetary-3', subject:'economics', concept:'monetary-policy', difficulty:2, version:QUESTION_VERSION,
    text:'中央銀行在公開市場買入政府公債，對貨幣供給的影響是？',
    answers:['減少貨幣供給（緊縮）','增加貨幣供給（寬鬆）——銀行持有更多資金可放款','對貨幣供給無影響','只影響匯率，不影響利率'],
    correct:1,
    explanation:'公開市場操作：中央銀行「買入」公債→將資金注入銀行體系→銀行可用資金增加→貨幣供給增加（寬鬆）；「賣出」公債→收回資金→貨幣供給減少（緊縮）。',
    source:'高中經濟學教材；中央銀行貨幣政策工具' },
  { id:'econ-monetary-4', subject:'economics', concept:'monetary-policy', difficulty:3, version:QUESTION_VERSION,
    text:'「量化寬鬆（QE）」政策的主要目的是？',
    answers:['提高利率以抑制通膨','在傳統降息空間耗盡（利率近零）時，透過大量購買資產注入資金，刺激借貸與投資','減少貨幣供給以穩定物價','限制銀行放款行為'],
    correct:1,
    explanation:'量化寬鬆（Quantitative Easing）：中央銀行大量購買長期公債或資產，向市場注入大量資金，在利率已接近零的情況下繼續提供刺激，典型案例是2008年金融危機後美國聯準會的政策。',
    source:'高中經濟學教材；2008年後全球貨幣政策' },
  { id:'econ-monetary-5', subject:'economics', concept:'monetary-policy', difficulty:2, version:QUESTION_VERSION,
    text:'「存款準備率」調高，對商業銀行放款能力的影響是？',
    answers:['放款能力增加','放款能力減少——須提撥更高比例的存款作為準備金，可用於放款的資金減少','完全沒有影響','使銀行破產'],
    correct:1,
    explanation:'存款準備率是銀行須提存中央銀行的比例；調高→銀行需提存更多準備→可放款資金減少→貨幣乘數效果降低→貨幣供給收縮（緊縮政策）。降低則相反。',
    source:'高中經濟學教材；中央銀行貨幣政策工具' },
  { id:'econ-fiscal-2', subject:'economics', concept:'fiscal-policy', difficulty:1, version:QUESTION_VERSION,
    text:'財政政策的主要工具是？',
    answers:['利率和存款準備率','政府支出和稅收','匯率干預','外匯存底管理'],
    correct:1,
    explanation:'財政政策由政府透過調整「政府支出」（公共建設、社會福利等）和「稅收」（加稅或減稅）來影響總需求，以穩定經濟；貨幣政策才是利率和存款準備率。',
    source:'高中經濟學教材；財政政策基本概念' },
  { id:'econ-fiscal-3', subject:'economics', concept:'fiscal-policy', difficulty:2, version:QUESTION_VERSION,
    text:'政府增稅或減少支出屬於哪種財政政策？',
    answers:['擴張性財政政策','緊縮性財政政策——降低政府赤字但也收縮總需求','中性財政政策','非常規貨幣政策'],
    correct:1,
    explanation:'緊縮性財政政策：增稅→人民可支配所得減少→消費降低；或削減政府支出→直接減少總需求。適用於景氣過熱或需要降低財政赤字時，但可能抑制經濟成長。',
    source:'高中經濟學教材；財政政策分類' },
  { id:'econ-fiscal-4', subject:'economics', concept:'fiscal-policy', difficulty:3, version:QUESTION_VERSION,
    text:'財政政策的「排擠效果」（crowding out）是指？',
    answers:['政府支出可以完全取代私人消費','政府借款增加→利率上升→民間投資減少，政府擴張支出的效果被部分抵消','政府稅收排擠掉個人儲蓄','高關稅排擠進口商品'],
    correct:1,
    explanation:'排擠效果：政府大量發行公債（借款）→資金市場需求增加→利率上漲→企業借貸成本提高→私人投資減少，政府支出增加帶來的擴張效果被部分抵銷。',
    source:'高中經濟學教材；財政政策效果' },
  { id:'econ-fiscal-5', subject:'economics', concept:'fiscal-policy', difficulty:2, version:QUESTION_VERSION,
    text:'「自動穩定機制」（automatic stabilizers）是指？',
    answers:['政府主動調整支出的行為','不需主動決策即自動發揮穩定效果的制度，如景氣衰退時失業補助自動增加、稅收自動減少','由中央銀行自動調整的機制','股市的自動回穩機制'],
    correct:1,
    explanation:'自動穩定機制：如累進所得稅（景氣好→高收入→高稅→抑制過熱）和失業保險（景氣差→失業增→補助增→支撐消費），無需立法或政策決定即自動對景氣週期產生穩定效果。',
    source:'高中經濟學教材；財政政策自動穩定機制' },
  { id:'econ-trade-2', subject:'economics', concept:'international-trade', difficulty:1, version:QUESTION_VERSION,
    text:'「絕對利益（absolute advantage）」與「比較利益」的差別是？',
    answers:['兩者完全相同','絕對利益是某國在某商品生產效率高於他國；比較利益考慮的是機會成本，即使沒有絕對利益也能受益於貿易','比較利益只適用於農產品','只有大國才有比較利益'],
    correct:1,
    explanation:'絕對利益（Adam Smith）：一國在某商品的生產效率高於他國；比較利益（David Ricardo）：即使一國在所有商品都有絕對利益，兩國仍可透過專注比較利益商品互換，雙方受益。比較利益是自由貿易的理論基礎。',
    source:'高中經濟學教材；國際貿易理論' },
  { id:'econ-trade-3', subject:'economics', concept:'international-trade', difficulty:2, version:QUESTION_VERSION,
    text:'關稅（tariff）的主要效果包含？',
    answers:['使進口商品價格下降，對消費者有利','使進口商品價格上升，保護本國產業但消費者需支付更高價格','讓所有人受益','只影響出口，不影響進口'],
    correct:1,
    explanation:'進口關稅提高了進口商品的最終售價：本國廠商競爭壓力減輕（保護作用）；消費者須支付更高價格（消費者剩餘下降）；政府獲得關稅收入；整體而言通常有無謂損失（deadweight loss）。',
    source:'高中經濟學教材；貿易政策分析' },
  { id:'econ-trade-4', subject:'economics', concept:'international-trade', difficulty:3, version:QUESTION_VERSION,
    text:'自由貿易協議（FTA）的主要目的是？',
    answers:['提高成員間的關稅','降低成員間的關稅與非關稅壁壘，促進貿易與投資流動','統一成員國貨幣','管制移民流動'],
    correct:1,
    explanation:'FTA（自由貿易協議）由締約國間協議降低或消除關稅、配額及技術性貿易障礙，促進彼此的貿易與投資；多邊FTA（如RCEP）則整合更大範圍的貿易規則。',
    source:'高中經濟學教材；世界貿易組織（WTO）與FTA' },
  { id:'econ-trade-5', subject:'economics', concept:'international-trade', difficulty:2, version:QUESTION_VERSION,
    text:'「匯率」對出口有何影響？',
    answers:['匯率對出口完全沒有影響','本國貨幣升值→本國商品對外國買家而言變貴→出口競爭力下降；貶值則反之','本幣升值總是對出口有利','只有進口受匯率影響'],
    correct:1,
    explanation:'匯率影響貿易競爭力：本幣升值（如台幣兌美元升值）→台灣出口商品以美元計算變貴→競爭力下降→出口可能減少；貶值→出口商品相對便宜→出口有利。',
    source:'高中經濟學教材；匯率與國際貿易' }
];

export const CONCEPTS = [...new Set(QUESTIONS.map(q => q.concept))];

// ── Concept reinforcement guides ─────────────────────────────────────────────
// Pre-written short explanations for each concept; no AI needed.
// Used by GET /api/practice/reinforce to guide students after wrong answers.
export type ConceptGuide = {
  concept: string; title: string; subject: Subject;
  summary: string;         // 2-3 sentences
  commonErrors: string[];  // typical mistakes
  keyPoints: string[];     // things to remember
};

export const CONCEPT_GUIDES: Record<string, ConceptGuide> = {
  'civil-burden-of-proof': {
    concept:'civil-burden-of-proof', title:'民事舉證責任', subject:'law',
    summary:'民事訴訟中，主張某事實的人通常要負責提出證據（民事訴訟法第277條）。法院不會主動為當事人蒐集有利證據。',
    commonErrors:['以為只要提告就會贏','誤認為被告要先自證清白','混淆民事與刑事的舉證標準'],
    keyPoints:['主張者舉證：你主張什麼事實，就要提出支持的證據','對方主張不實，也應由主張方舉證，而非要求你「證明自己沒做」','舉證不足時，主張無法成立']
  },
  'evidence-types': {
    concept:'evidence-types', title:'直接證據與傳聞證據', subject:'law',
    summary:'直接證據是當事人親眼見聞的事實；傳聞證據是轉述他人說法，效力較弱，需查證原始來源才能使用。',
    commonErrors:['把「聽說」等同於「親眼看到」','認為傳聞不能當作任何參考','混淆物證與證人陳述'],
    keyPoints:['直接證據：自己親眼、親耳感知的事實','傳聞：轉述別人說的話，不能直接認定事實','一份證據能證明什麼、不能證明什麼，都要分別釐清']
  },
  'presumption-of-innocence': {
    concept:'presumption-of-innocence', title:'無罪推定原則', subject:'law',
    summary:'刑事訴訟中，被告在有罪判決確定前，法律上視為無罪（刑事訴訟法第154條）。舉證責任在國家（檢察官），不在被告。',
    commonErrors:['認為被逮捕或起訴就等於有罪','認為被告保持沉默就表示心虛','認為社會輿論可以取代法院判決'],
    keyPoints:['法院宣判有罪確定前：法律上是無罪的','行使緘默權是被告的合法選擇，不得因此不利認定','檢察官要拿出足夠證據，而非被告自清']
  },
  'juvenile-protection': {
    concept:'juvenile-protection', title:'少年事件處理法精神', subject:'law',
    summary:'少年事件以保護、教育為優先，而非懲罰（少年事件處理法第1條）。程序強調釐清事實、了解背景，並討論適當支持措施。',
    commonErrors:['認為少年程序就是縮小版的成人刑事程序','誤以為歸還物品或道歉後就不需調查','以為有輔導方案就代表已認罪'],
    keyPoints:['保護事件重在健全成長，非懲罰','事實釐清與支持措施是分開的兩件事','少年有陳述與程序保障的權利']
  },
  'civil-criminal-distinction': {
    concept:'civil-criminal-distinction', title:'民事與刑事的區別', subject:'law',
    summary:'民事訴訟解決私人間的財產或侵權爭議；刑事訴訟是國家代表社會追究犯罪行為。兩者可以並行，但目的、程序和效果都不同。',
    commonErrors:['以為民事輸了就等同於刑事有罪','認為刑事判無罪就代表民事也不用賠','誤以為同一件事只能選一種訴訟'],
    keyPoints:['民事：私人 vs 私人，解決賠償或履約問題','刑事：國家 vs 被告，追究刑事責任','同一事件可以同時有民事索賠和刑事告訴']
  },
  'legal-aid': {
    concept:'legal-aid', title:'法律扶助制度', subject:'law',
    summary:'法律扶助基金會針對資力不足且有需求的當事人提供律師協助，適用於民事、刑事、行政等多種案件，須申請審查核准。',
    commonErrors:['以為法律扶助適用所有人且不需審查','混淆法律扶助與指定辯護（僅限刑事被告特定情形）','以為只有刑事案件才能申請'],
    keyPoints:['申請→審查→核准：有一套程序，不是自動取得','民事、刑事、行政都可能適用，依個案而定','法院指定辯護（刑事）≠ 法律扶助，兩者制度不同']
  },
  'causation': {
    concept:'causation', title:'侵權行為的因果關係', subject:'law',
    summary:'民事損害賠償需要三個要素同時成立：加害行為、損害結果、兩者之間的相當因果關係。缺少任一要素就無法成立。',
    commonErrors:['以為有損害就一定有人要賠','認為「在場」等於「造成損害」','忽略行為與損害之間的因果連結'],
    keyPoints:['要同時有：行為＋損害＋因果關係，三者缺一不可','「相當因果關係」：依一般經驗判斷，該行為通常會造成該損害','損害金額再大，若無因果關係，也無法主張賠償']
  },
  'fundamental-rights': {
    concept:'fundamental-rights', title:'憲法基本人身自由', subject:'civics',
    summary:'憲法第8條保障人身自由：人民非依法定程序，不得逮捕、拘禁、審問或處罰。這是防止國家任意剝奪人身自由的根本保障。',
    commonErrors:['以為警察可以無限期拘留任何人','認為被帶走問話就等於被拘禁','誤以為政府想怎樣就能怎樣'],
    keyPoints:['人身自由是受憲法直接保障的基本權利','限制需有法律依據並符合正當程序','非法拘禁是違憲行為，當事人有救濟管道']
  },
  'due-process': {
    concept:'due-process', title:'正當法律程序', subject:'civics',
    summary:'正當法律程序要求國家限制人民權利時，須有法律授權、符合程序正義（公平聽證、告知理由等），且手段與目的要符合比例原則。',
    commonErrors:['以為結果正確就不必在乎程序','認為緊急情況下可以完全不遵守程序','誤以為程序是阻礙效率的形式主義'],
    keyPoints:['程序正義本身就是重要的價值，不只是手段','聽證、告知理由、給予陳述機會，都是程序的核心','違反正當程序，即使結果正確，仍可能違憲或違法']
  },
  'separation-of-powers': {
    concept:'separation-of-powers', title:'三權分立與制衡', subject:'civics',
    summary:'立法、行政、司法三權各有職掌，且互相制衡。立法院制定法律、監督行政；行政院執行政策；司法院解釋憲法、審理案件。',
    commonErrors:['以為三權是完全獨立毫不往來','認為行政院可以直接命令法院','誤以為多數決就能無限擴張行政權力'],
    keyPoints:['分立：三個機關各有專屬職權','制衡：一個機關能對另一個機關踩剎車','目的：防止任何一方濫用權力，保障人民自由']
  },
  'supply-demand': {
    concept:'supply-demand', title:'供給與需求', subject:'economics',
    summary:'市場價格由供給與需求的均衡決定。需求增加或供給減少，價格通常上升；反之則下降。這是市場資源配置的核心機制。',
    commonErrors:['混淆「需求量變動」和「需求本身移動」','以為價格上升一定是供給商操縱','誤以為均衡一定對社會最有利'],
    keyPoints:['需求曲線右移（需求增加）→ 均衡價格上升、數量增加','供給曲線左移（供給減少）→ 均衡價格上升、數量減少','市場均衡是供給方和需求方都願意交易的點']
  },
  'opportunity-cost': {
    concept:'opportunity-cost', title:'機會成本', subject:'economics',
    summary:'做出任何選擇都意味著放棄其他選項。機會成本是你放棄的「次佳選擇的價值」，不是貨幣成本，也不是所有放棄選項的總和。',
    commonErrors:['把機會成本和金錢成本混淆','以為機會成本是所有放棄選項的總和','忽略時間、精力等非金錢的機會成本'],
    keyPoints:['機會成本 = 次佳選擇的價值（只有一個，不是加總）','選擇A的機會成本是放棄的B，不是放棄的B+C+D','即使某件事「免費」，時間也有機會成本']
  },
  'market-failure': {
    concept:'market-failure', title:'市場失靈與外部性', subject:'economics',
    summary:'市場有時無法有效分配資源，例如外部性（污染）、公共財、資訊不對稱等，這時政府可能需要介入。外部性是行為對第三者的影響未被市場價格反映。',
    commonErrors:['認為市場永遠是最有效率的，不需政府介入','把負外部性和稅收混淆','以為只有環境污染才算外部性'],
    keyPoints:['負外部性：行為產生社會成本但不由行為者承擔（如污染）','正外部性：行為產生社會利益但行為者得不到全部回報（如教育）','政府工具：課稅、補貼、法規等，目的是讓外部成本/效益內部化']
  },
  'contract-formation': {
    concept:'contract-formation', title:'契約成立要件', subject:'law',
    summary:'契約由「要約」與「承諾」兩個意思表示合致而成立（民法第153條）。要約是拘束性的邀請，承諾必須在有效期間內完全同意要約內容。',
    commonErrors:['以為一定要書面才算契約','以為口頭契約無效','誤以為契約要公證才生效'],
    keyPoints:['要約＋承諾＝契約成立，不需書面（但書面有利於證明）','承諾內容若與要約不同，視為新要約','口頭契約原則上有效，只是舉證困難']
  },
  'intellectual-property': {
    concept:'intellectual-property', title:'著作權保護', subject:'law',
    summary:'著作完成時即自動享有著作權，不需申請登記（著作權法第10條）。著作財產權有期限（一般為著作人終身加50年），著作人格權則永久存在。',
    commonErrors:['以為要向政府申請才有著作權','認為加了©符號才受保護','以為免費使用就不侵權'],
    keyPoints:['創作完成即享有著作權，無需登記','合理使用（fair use）有條件允許部分使用，但非無限制','轉載或引用仍須標示來源，不能去除著作人姓名']
  },
  'consumer-protection': {
    concept:'consumer-protection', title:'消費者保護', subject:'law',
    summary:'消費者保護法對企業經營者採嚴格責任，舉證責任倒置：企業須證明商品安全，而非消費者自證商品有瑕疵，以彌補雙方資訊不對等。',
    commonErrors:['以為消費者必須自己證明一切','認為只要退貨就等於解決問題','誤以為保固期等於消費者保護法的保障期限'],
    keyPoints:['企業對商品安全負嚴格責任','消費者只需舉證受有損害即可主張','7天鑑賞期（網購）是特別保障，非所有商品均適用']
  },
  'legal-representation': {
    concept:'legal-representation', title:'限制行為能力與代理', subject:'law',
    summary:'7歲以上未成年人為限制行為能力人，獨自進行的法律行為效力未定，須法定代理人（通常是父母）允許或事後承認（民法第77條）。',
    commonErrors:['以為未成年人完全不能簽任何契約','認為只要成年就不需任何同意','誤以為輕微日常行為也需要父母同意'],
    keyPoints:['未滿7歲：無行為能力，由法定代理人代為','7歲以上未成年：限制行為能力，需法代允許或承認','純獲法律利益或日常生活必需行為：例外有效']
  },
  'tort-liability': {
    concept:'tort-liability', title:'民事侵權責任', subject:'law',
    summary:'民法第184條規定：故意或過失不法侵害他人權利，須負損害賠償責任。侵權行為可同時構成刑事犯罪，但兩者程序與目的不同。',
    commonErrors:['以為刑事無罪就不用民事賠償','認為只有故意才要賠，過失不用','混淆精神慰撫金與財產損害賠償'],
    keyPoints:['民事侵權不需要達到刑事犯罪標準','過失（不小心）也可能構成侵權','刑事和民事可以同時進行，互不影響']
  },
  'judicial-remedy': {
    concept:'judicial-remedy', title:'司法救濟途徑', subject:'law',
    summary:'我國採三級三審：地方法院→高等法院→最高法院。對判決不服，在法定期間內向上級法院提起上訴；行政事件另有行政訴訟體系。',
    commonErrors:['以為任何案件都能上訴三次','認為向總統或立委陳情等於正式救濟','混淆民事、刑事、行政三種訴訟體系'],
    keyPoints:['三級三審：每一審都有期限，超過就確定','第三審（最高法院）通常只審法律問題，不重新審事實','行政處分：訴願→行政訴訟，與普通法院體系不同']
  },
  'election-system': {
    concept:'election-system', title:'選舉制度', subject:'civics',
    summary:'立法院採單一選區兩票制：一票選區域立委（相對多數），一票選政黨（比例分配不分區席次）。不同選舉制度影響政黨生態與代表性。',
    commonErrors:['混淆區域票和政黨票的功能','以為得票最多者一定能分配更多不分區','認為選舉制度和結果無關'],
    keyPoints:['兩票：一票給候選人（區域），一票給政黨（不分區）','不分區依政黨得票比例分配，須通過5%門檻','不同制度（比例代表、多數決）各有代表性與穩定性的取捨']
  },
  'local-autonomy': {
    concept:'local-autonomy', title:'地方自治', subject:'civics',
    summary:'地方自治讓地方居民依法自行選舉代表、管理地方事務，是民主政治的延伸。地方政府有自治立法權，但仍受憲法與中央法令拘束。',
    commonErrors:['以為地方可以完全不受中央管轄','認為自治就是分裂','誤以為地方條例可以牴觸中央法律'],
    keyPoints:['地方自治是憲法保障的制度（憲法第10章）','地方法規不得牴觸上位規範（中央法律）','直轄市、縣（市）、鄉（鎮、市）層級各有不同自治範圍']
  },
  'administrative-remedy': {
    concept:'administrative-remedy', title:'行政救濟', subject:'civics',
    summary:'人民對行政機關處分不服，可先提訴願（向上級機關），對訴願結果不服再提行政訴訟（向行政法院）。這是保障人民對抗行政權的重要機制。',
    commonErrors:['直接跳過訴願提行政訴訟（通常不合法）','以為向民代陳情等於正式救濟','誤認為行政訴訟和普通法院一樣'],
    keyPoints:['訴願先行原則：多數情形須先訴願','訴願→行政訴訟：二階段救濟','行政法院專門審理行政事件，與民事、刑事法院分開']
  },
  'media-literacy': {
    concept:'media-literacy', title:'媒體素養', subject:'civics',
    summary:'媒體素養是分析、評估媒體內容的能力，包括辨識資訊來源、查核事實、分析報導立場，以及理解媒體如何建構現實。',
    commonErrors:['以為主流媒體就一定客觀','認為網路上的資訊都是真的','誤以為只看一個來源就足夠'],
    keyPoints:['交叉查核（cross-check）：比對多個可信來源','分辨新聞（事實）vs 評論（意見）','留意標題黨與斷章取義，閱讀全文再判斷']
  },
  'civil-society': {
    concept:'civil-society', title:'公民社會與NGO', subject:'civics',
    summary:'公民社會由獨立於政府和市場之外的組織與個人組成，NGO（非政府組織）是其重要成員，以倡議公共利益、提供社會服務或監督公權力為目的。',
    commonErrors:['以為NGO一定反對政府','認為只有大型組織才算NGO','誤以為公民社會和政府必然對立'],
    keyPoints:['NGO：非政府、非營利、有組織的公民團體','功能：倡議、服務、監督、國際合作','公民參與不只是選舉，包括結社、集會、請願等']
  },
  'gdp-growth': {
    concept:'gdp-growth', title:'GDP 與經濟成長', subject:'economics',
    summary:'GDP 衡量一定期間內境內生產的最終商品與服務市場總值。GDP 成長代表經濟擴張，但無法反映分配是否公平或環境成本。',
    commonErrors:['混淆GDP和GNP（國民生產毛額）','以為GDP高就代表人民生活水準一定高','忽略GDP不計算非市場活動如家務勞動'],
    keyPoints:['GDP：境內生產（不論國籍）；GNP：本國人生產（不論地點）','人均GDP更能反映生活水準，但仍忽略分配','GDP成長不等於所有人都變富裕']
  },
  'inflation-deflation': {
    concept:'inflation-deflation', title:'通膨與通縮', subject:'economics',
    summary:'通膨是物價普遍持續上漲，導致貨幣購買力下降。通縮是物價普遍持續下跌，看似有利但可能引發消費遞延與經濟衰退的惡性循環。',
    commonErrors:['以為物價上漲一定是壞事','認為通縮（物價下跌）一定有利','誤以為通膨只有壞處，沒有任何好處'],
    keyPoints:['溫和通膨（約2%）通常被視為健康的經濟信號','惡性通膨讓貨幣嚴重貶值，打亂資源配置','通縮可能讓消費者等待更低價格，形成需求萎縮的惡性循環']
  },
  'monetary-policy': {
    concept:'monetary-policy', title:'貨幣政策', subject:'economics',
    summary:'中央銀行透過調整利率、存款準備率或公開市場操作，影響貨幣供給與借貸成本，進而管理通膨與穩定經濟。',
    commonErrors:['混淆貨幣政策（央行）和財政政策（政府）','以為升息一定對股市不好','認為央行可以同時控制通膨和促進成長（兩難困境）'],
    keyPoints:['升息：抑制借貸與消費，降通膨但可能減緩成長','降息：刺激借貸與投資，促成長但可能推升通膨','貨幣政策效果有時間落差，不是立竿見影']
  },
  'fiscal-policy': {
    concept:'fiscal-policy', title:'財政政策', subject:'economics',
    summary:'財政政策由政府透過調整稅收和支出影響總需求。景氣衰退時擴張（增支出／減稅），景氣過熱時緊縮（減支出／加稅）。',
    commonErrors:['混淆財政政策和貨幣政策的執行者','認為政府赤字一定是壞事','以為減稅一定能刺激成長'],
    keyPoints:['擴張財政：增加政府支出或減稅→刺激需求','緊縮財政：減少支出或加稅→冷卻過熱經濟','財政政策立法程序較長，時效性不如貨幣政策靈活']
  },
  'international-trade': {
    concept:'international-trade', title:'比較利益與國際貿易', subject:'economics',
    summary:'比較利益原則說明：即使一國在所有商品上都效率較高，各國仍能透過專業分工與貿易互利。關鍵是機會成本的比較，而非絕對效率。',
    commonErrors:['混淆比較利益和絕對利益','認為貿易一定有贏家和輸家','以為保護主義一定能使本國更繁榮'],
    keyPoints:['比較利益：看機會成本，而非絕對生產量','自由貿易理論上使雙方消費可能性擴大','實際上貿易有分配問題：有些人得益，有些人受損']
  }
};
